In [2]:
from selenium import webdriver
from time import sleep
from scrapy.selector import Selector
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("--headless")


chromedriver = "/home/btan/Documents/chromedriver"
driver = webdriver.Chrome(chromedriver, options = chrome_options)

In [2]:
##############################################################
# section 1: get the list of job listings
##############################################################

In [3]:
##############################################################
# section 1a: get all the url of job listings
##############################################################

In [4]:
##############################################################
# this code is to generate the url for search page
##############################################################


def url_generator (site, title, page):
    
    # create the basic format. use with .format(job_title, page)
    url_base_careersfuture = 'https://www.mycareersfuture.sg/search?search={}&sortBy=new_posting_date&page={}'
 
    websites = {
        
        'careersfuture':
                {
                    'Data_Analyst': url_base_careersfuture.format('Data%20Analyst',page),
                    'Senior_Data_Analyst': url_base_careersfuture.format('Senior%20Data%20Analyst',page),
                    'Data_Manager': url_base_careersfuture.format('Data%20Manager',page),
                    'Data_Architect': url_base_careersfuture.format('Data%20Architect',page),
                    'Senior_Data_Architect': url_base_careersfuture.format('Senior%20Data%20Architect',page),
                    'Data_Analytics': url_base_careersfuture.format('Data%20Analytics',page),
                    'Data_Scientist': url_base_careersfuture.format('Data%20Scientist',page),
                    'Data_Science': url_base_careersfuture.format('Data%20Science',page),
                    'Business_Analytics': url_base_careersfuture.format('Business%20Analytics',page),
                    'Financial_Analytics': url_base_careersfuture.format('Financial%20Analytics',page),
                    'Marketing_Analytics': url_base_careersfuture.format('Marketing%20Analytics',page),
                    'Data_Visualisation': url_base_careersfuture.format('Data%20Visualisation',page),
                    'Data_Operations': url_base_careersfuture.format('Data%20Operations',page),
                    'Data_Strategist': url_base_careersfuture.format('Data%20Strategist',page),
                    'Data_Engineer': url_base_careersfuture.format('Data%20Engineer',page),
                    'Data_Intern': url_base_careersfuture.format('Data%20Intern',page),
                    'Data_Lead': url_base_careersfuture.format('Data%20Lead',page),
                    'Data_Consultant': url_base_careersfuture.format('Data%20Consultant',page),
                    'Machine_Learning': url_base_careersfuture.format('Machine%20Learning',page),
                    'Deep_Learning': url_base_careersfuture.format('Deep%20Learning',page),
                    'Big_Data': url_base_careersfuture.format('Big%20Data',page),
                    'Business_Intelligence': url_base_careersfuture.format('Business%20Intelligence',page),        
                
                } 
        
    }
    
    return websites[site][title]

In [5]:
##############################################################
# this code is to command chromedriver to obtain html
##############################################################

def get_html (site):
    
    #driver = webdriver.Chrome(chromedriver, chrome_options = chrome_options)
    driver.get(site)
    sleep(3)
    html = driver.page_source
    #driver.close()

    return html

In [6]:
##############################################################
# this code is to create a list of search criterias
##############################################################

sites = ['careersfuture']

job_titles = {
    
    'careersfuture':['Data_Analyst','Senior_Data_Analyst',
                     'Data_Manager', 'Data_Architect',
                     'Senior_Data_Architect', 'Data_Analytics',
                     'Data_Scientist', 'Data_Science',
                     'Business_Analytics', 'Financial_Analytics',
                     'Marketing_Analytics', 'Data_Visualisation',
                     'Data_Operations', 'Data_Strategist',
                     'Data_Engineer', 'Data_Intern',
                     'Data_Lead', 'Data_Consultant',
                     'Machine_Learning', 'Deep_Learning',
                     'Big_Data', 'Business_Intelligence'                    
                    ]

}

In [7]:
# this list will contain all the job listings url
job_links = []

In [8]:
##############################################################
# this code is to create a list of job listings URL
##############################################################

# scan through each site
for site in sites:
    
    # for careersfuture only
    if site == 'careersfuture':
        # scan through each job title
        for job_title in job_titles[site]:

            # load the first page, see how many results available

            html = get_html( url_generator(site,job_title,0))
            results_counts = Selector(text=html).xpath('//*[@id="search-results-message"]/div/text()').extract()
            
            try:
                
                num_pages = int(np.ceil(int(results_counts[0].replace(' jobs found','')) / 20.))+2
            except:
                num_pages = 10
            #print('Update: Found {} results for {} from {}'.format(results_counts[0].replace(' jobs found',''), job_title, site))

            # scan through each page
            for page in range(num_pages):

                html = get_html( url_generator(site, job_title, page))
                job_url = Selector(text=html).xpath('//*[@class="bg-white mb3 w-100 dib v-top pa3 no-underline flex-ns flex-wrap JobCard__card___22xP3"]/@href').extract()
                for item in job_url:         
                     job_links.append('https://www.mycareersfuture.sg' + item)
                print('Update: Added {} entries for page {} of from {}-{}'.format(len(job_url), page, site, job_title))

print('Total of {} job entries found.'.format(len(job_links)))

Update: Added 20 entries for page 0 of from careersfuture-Data_Analyst
Update: Added 20 entries for page 1 of from careersfuture-Data_Analyst
Update: Added 20 entries for page 2 of from careersfuture-Data_Analyst
Update: Added 20 entries for page 3 of from careersfuture-Data_Analyst
Update: Added 20 entries for page 4 of from careersfuture-Data_Analyst
Update: Added 3 entries for page 5 of from careersfuture-Data_Analyst
Update: Added 0 entries for page 6 of from careersfuture-Data_Analyst
Update: Added 0 entries for page 7 of from careersfuture-Data_Analyst
Update: Added 20 entries for page 0 of from careersfuture-Senior_Data_Analyst
Update: Added 20 entries for page 1 of from careersfuture-Senior_Data_Analyst
Update: Added 20 entries for page 2 of from careersfuture-Senior_Data_Analyst
Update: Added 20 entries for page 3 of from careersfuture-Senior_Data_Analyst
Update: Added 16 entries for page 4 of from careersfuture-Senior_Data_Analyst
Update: Added 0 entries for page 5 of from careersfuture-Senior_Data_Analyst
Update: Added 0 entries for page 6 of from careersfuture-Senior_Data_Analyst
Update: Added 20 entries for page 0 of from careersfuture-Data_Manager
Update: Added 20 entries for page 1 of from careersfuture-Data_Manager
Update: Added 20 entries for page 2 of from careersfuture-Data_Manager
Update: Added 1 entries for page 3 of from careersfuture-Data_Manager
Update: Added 0 entries for page 4 of from careersfuture-Data_Manager
Update: Added 0 entries for page 5 of from careersfuture-Data_Manager
Update: Added 20 entries for page 0 of from careersfuture-Data_Architect
Update: Added 15 entries for page 1 of from careersfuture-Data_Architect
Update: Added 0 entries for page 2 of from careersfuture-Data_Architect
Update: Added 0 entries for page 3 of from careersfuture-Data_Architect
Update: Added 20 entries for page 0 of from careersfuture-Senior_Data_Architect
Update: Added 6 entries for page 1 of from careersfuture-Senior_Data_Architect
Update: Added 0 entries for page 2 of from careersfuture-Senior_Data_Architect
Update: Added 0 entries for page 3 of from careersfuture-Senior_Data_Architect
Update: Added 20 entries for page 0 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 1 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 2 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 3 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 4 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 5 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 6 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 7 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 8 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 9 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 10 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 11 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 12 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 13 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 14 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 15 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 16 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 17 of from careersfuture-Data_Analytics
Update: Added 15 entries for page 18 of from careersfuture-Data_Analytics
Update: Added 0 entries for page 19 of from careersfuture-Data_Analytics
Update: Added 0 entries for page 20 of from careersfuture-Data_Analytics
Update: Added 20 entries for page 0 of from careersfuture-Data_Scientist
Update: Added 20 entries for page 1 of from careersfuture-Data_Scientist
Update: Added 20 entries for page 2 of from careersfuture-Data_Scientist
Update: Added 20 entries for page 3 of from careersfuture-Data_Scientist
Update: Added 20 entries for page 4 of from careersfuture-Data_Scientist
Update: Added 13 entries for page 5 of from careersfuture-Data_Scientist
Update: Added 0 entries for page 6 of from careersfuture-Data_Scientist
Update: Added 0 entries for page 7 of from careersfuture-Data_Scientist
Update: Added 0 entries for page 0 of from careersfuture-Data_Science
Update: Added 20 entries for page 1 of from careersfuture-Data_Science
Update: Added 20 entries for page 2 of from careersfuture-Data_Science
Update: Added 20 entries for page 3 of from careersfuture-Data_Science
Update: Added 20 entries for page 4 of from careersfuture-Data_Science
Update: Added 20 entries for page 5 of from careersfuture-Data_Science
Update: Added 20 entries for page 6 of from careersfuture-Data_Science
Update: Added 7 entries for page 7 of from careersfuture-Data_Science
Update: Added 0 entries for page 8 of from careersfuture-Data_Science
Update: Added 0 entries for page 9 of from careersfuture-Data_Science
Update: Added 20 entries for page 0 of from careersfuture-Business_Analytics
Update: Added 15 entries for page 1 of from careersfuture-Business_Analytics
Update: Added 0 entries for page 2 of from careersfuture-Business_Analytics
Update: Added 0 entries for page 3 of from careersfuture-Business_Analytics
Update: Added 12 entries for page 0 of from careersfuture-Financial_Analytics
Update: Added 0 entries for page 1 of from careersfuture-Financial_Analytics
Update: Added 0 entries for page 2 of from careersfuture-Financial_Analytics
Update: Added 20 entries for page 0 of from careersfuture-Marketing_Analytics
Update: Added 0 entries for page 1 of from careersfuture-Marketing_Analytics
Update: Added 0 entries for page 2 of from careersfuture-Marketing_Analytics
Update: Added 17 entries for page 0 of from careersfuture-Data_Visualisation
Update: Added 0 entries for page 1 of from careersfuture-Data_Visualisation
Update: Added 0 entries for page 2 of from careersfuture-Data_Visualisation
Update: Added 20 entries for page 0 of from careersfuture-Data_Operations
Update: Added 1 entries for page 1 of from careersfuture-Data_Operations
Update: Added 0 entries for page 2 of from careersfuture-Data_Operations
Update: Added 0 entries for page 3 of from careersfuture-Data_Operations
Update: Added 1 entries for page 0 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 1 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 2 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 3 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 4 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 5 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 6 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 7 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 8 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 9 of from careersfuture-Data_Strategist
Update: Added 0 entries for page 0 of from careersfuture-Data_Engineer
Update: Added 20 entries for page 1 of from careersfuture-Data_Engineer
Update: Added 20 entries for page 2 of from careersfuture-Data_Engineer
Update: Added 20 entries for page 3 of from careersfuture-Data_Engineer
Update: Added 20 entries for page 4 of from careersfuture-Data_Engineer
Update: Added 20 entries for page 5 of from careersfuture-Data_Engineer
Update: Added 14 entries for page 6 of from careersfuture-Data_Engineer
Update: Added 0 entries for page 7 of from careersfuture-Data_Engineer
Update: Added 0 entries for page 8 of from careersfuture-Data_Engineer
Update: Added 1 entries for page 0 of from careersfuture-Data_Intern
Update: Added 0 entries for page 1 of from careersfuture-Data_Intern
Update: Added 0 entries for page 2 of from careersfuture-Data_Intern
Update: Added 0 entries for page 3 of from careersfuture-Data_Intern
Update: Added 0 entries for page 4 of from careersfuture-Data_Intern
Update: Added 0 entries for page 5 of from careersfuture-Data_Intern
Update: Added 0 entries for page 6 of from careersfuture-Data_Intern
Update: Added 0 entries for page 7 of from careersfuture-Data_Intern
Update: Added 0 entries for page 8 of from careersfuture-Data_Intern

Update: Added 0 entries for page 9 of from careersfuture-Data_Intern
Update: Added 16 entries for page 0 of from careersfuture-Data_Lead
Update: Added 0 entries for page 1 of from careersfuture-Data_Lead
Update: Added 0 entries for page 2 of from careersfuture-Data_Lead
Update: Added 18 entries for page 0 of from careersfuture-Data_Consultant
Update: Added 0 entries for page 1 of from careersfuture-Data_Consultant
Update: Added 0 entries for page 2 of from careersfuture-Data_Consultant
Update: Added 20 entries for page 0 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 1 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 2 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 3 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 4 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 5 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 6 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 7 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 8 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 9 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 10 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 11 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 12 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 13 of from careersfuture-Machine_Learning
Update: Added 17 entries for page 14 of from careersfuture-Machine_Learning
Update: Added 0 entries for page 15 of from careersfuture-Machine_Learning
Update: Added 0 entries for page 16 of from careersfuture-Machine_Learning
Update: Added 20 entries for page 0 of from careersfuture-Deep_Learning
Update: Added 20 entries for page 1 of from careersfuture-Deep_Learning
Update: Added 20 entries for page 2 of from careersfuture-Deep_Learning
Update: Added 17 entries for page 3 of from careersfuture-Deep_Learning
Update: Added 0 entries for page 4 of from careersfuture-Deep_Learning
Update: Added 0 entries for page 5 of from careersfuture-Deep_Learning
Update: Added 20 entries for page 0 of from careersfuture-Big_Data
Update: Added 20 entries for page 1 of from careersfuture-Big_Data
Update: Added 20 entries for page 2 of from careersfuture-Big_Data
Update: Added 20 entries for page 3 of from careersfuture-Big_Data
Update: Added 20 entries for page 4 of from careersfuture-Big_Data
Update: Added 20 entries for page 5 of from careersfuture-Big_Data
Update: Added 20 entries for page 6 of from careersfuture-Big_Data
Update: Added 20 entries for page 7 of from careersfuture-Big_Data
Update: Added 20 entries for page 8 of from careersfuture-Big_Data
Update: Added 20 entries for page 9 of from careersfuture-Big_Data
Update: Added 20 entries for page 10 of from careersfuture-Big_Data
Update: Added 20 entries for page 11 of from careersfuture-Big_Data
Update: Added 18 entries for page 12 of from careersfuture-Big_Data
Update: Added 0 entries for page 13 of from careersfuture-Big_Data
Update: Added 0 entries for page 14 of from careersfuture-Big_Data
Update: Added 20 entries for page 0 of from careersfuture-Business_Intelligence
Update: Added 20 entries for page 1 of from careersfuture-Business_Intelligence
Update: Added 20 entries for page 2 of from careersfuture-Business_Intelligence
Update: Added 20 entries for page 3 of from careersfuture-Business_Intelligence
Update: Added 20 entries for page 4 of from careersfuture-Business_Intelligence
Update: Added 3 entries for page 5 of from careersfuture-Business_Intelligence
Update: Added 0 entries for page 6 of from careersfuture-Business_Intelligence
Update: Added 0 entries for page 7 of from careersfuture-Business_Intelligence
Total of 1926 job entries found.

In [9]:
##############################################################
# section 1b: get job listing details from URL collected
##############################################################

In [10]:
# create a list for collecting all job listing details
job_details = pd.DataFrame()
job_pull_error_list = []
job_pull_error_list_2 = []

In [11]:
##############################################################
# this function is to get join details from careerfuture url
# and return the job details
##############################################################

def pull_job_details_mycareersfuture (url):
    
    # load page, get page source, close page
    #driver = webdriver.Chrome(chromedriver, chrome_options = chrome_options)
    html = get_html(url)
    
    # get the job details
    job_id = Selector(text=html).xpath('//*[@data-cy="jobinfo__jobpostid--span"]/text()').extract()[0].replace(" ",'')
    job_title = Selector(text=html).xpath('//*[@id="job_title"]/text()').extract()[0]

    company_name = Selector(text=html).xpath('//*[@name="company"]/text()').extract()[0]
    # cater for cases where company name is undisclosed
    try:
        company_address = Selector(text=html).xpath('//*[@href="#location_map"]/text()').extract()[0]
    except:
        company_address = np.nan

        
    employment_type = Selector(text=html).xpath('//*[@id="employment_type"]/text()').extract()[0]
        
    seniority = Selector(text=html).xpath('//*[@id="seniority"]/text()').extract()[0]

    job_category = Selector(text=html).xpath('//*[@id="job-categories"]/text()').extract()[0]
    job_url = url
    job_description = Selector(text=html).xpath('//*[@id="description-content"]/p/text()').extract()
    job_requirements = Selector(text=html).xpath('//*[@id="requirements-content"]/ul/li/text()').extract()
    
    job_skills = Selector(text=html).xpath('//*[@id="skills-needed"]/div/div/label/text()').extract()

    # salary could be empty. use try/except
    try:
        pay_min = Selector(text=html).xpath('//*[@class="dib"]/text()').extract()[0]
        pay_max = Selector(text=html).xpath('//*[@class="dib"]/text()').extract()[1]
        pay_type = Selector(text=html).xpath('//*[@class="salary_type dib f5 fw4 black-60 pr1 i pb"]/text()').extract()[0]
    except:
        pay_min = np.nan
        pay_max = np.nan
        pay_type = np.nan

    post_date = Selector(text=html).xpath('//*[@id="last_posted_date"]/text()').extract()[0].replace('Posted ','')
    close_date = Selector(text=html).xpath('//*[@class="purple f6 fw4 pr3 pt2 dib"]/text()').extract()[0].replace('Closing on ','')

    return [job_id, job_title, company_name, company_address,  
                                      job_category, job_url, job_description, job_requirements,
                                      employment_type, seniority, job_skills,
                                      pay_min, pay_max, pay_type, post_date, close_date]

In [12]:
##############################################################
# this function is to get join details from the URL provided
# and return the job details
##############################################################

def pull_job_details(url, web):
    
    if web == 'mcf':
        return pull_job_details_mycareersfuture(url)

In [13]:
##############################################################
# populate the 'job_details' dataframe with url in 'job_links'
##############################################################

for row_count in range(len(job_links)):
    print('Update: Pulling data for job {}'.format(row_count))
    try:
        job_details = job_details.append([pull_job_details(job_links[row_count], 'mcf')])
    except:
        print('Error: Error pulling data for job {}, executing attempt 2'.format(row_count))
        try:
            job_details = job_details.append([pull_job_details(job_links[row_count], 'mcf')])
        except:
            print('Error: Error pulling data for job {}, executing attempt 3'.format(row_count))
            try:
                job_details = job_details.append([pull_job_details(job_links[row_count], 'mcf')])
            except:
                print('Error: Error pulling data for job {}, ignoring row'.format(row_count))
                job_pull_error_list.append(row_count)

Update: Pulling data for job 0
Update: Pulling data for job 1
Update: Pulling data for job 2
Update: Pulling data for job 3
Update: Pulling data for job 4
Update: Pulling data for job 5
Update: Pulling data for job 6
Update: Pulling data for job 7
Update: Pulling data for job 8
Update: Pulling data for job 9
Update: Pulling data for job 10
Update: Pulling data for job 11
Update: Pulling data for job 12
Update: Pulling data for job 13
Update: Pulling data for job 14
Update: Pulling data for job 15
Update: Pulling data for job 16
Update: Pulling data for job 17
Update: Pulling data for job 18
Update: Pulling data for job 19
Error: Error pulling data for job 19, executing attempt 2
Error: Error pulling data for job 19, executing attempt 3
Error: Error pulling data for job 19, ignoring row
Update: Pulling data for job 20
Update: Pulling data for job 21
Update: Pulling data for job 22
Update: Pulling data for job 23
Update: Pulling data for job 24
Update: Pulling data for job 25
Update: Pulling data for job 26
Update: Pulling data for job 27
Update: Pulling data for job 28
Update: Pulling data for job 29
Update: Pulling data for job 30
Update: Pulling data for job 31
Error: Error pulling data for job 31, executing attempt 2
Error: Error pulling data for job 31, executing attempt 3
Update: Pulling data for job 32
Error: Error pulling data for job 32, executing attempt 2
Update: Pulling data for job 33
Update: Pulling data for job 34
Error: Error pulling data for job 34, executing attempt 2
Error: Error pulling data for job 34, executing attempt 3
Error: Error pulling data for job 34, ignoring row
Update: Pulling data for job 35
Update: Pulling data for job 36
Update: Pulling data for job 37
Error: Error pulling data for job 37, executing attempt 2
Update: Pulling data for job 38
Update: Pulling data for job 39
Error: Error pulling data for job 39, executing attempt 2
Update: Pulling data for job 40
Update: Pulling data for job 41
Update: Pulling data for job 42
Update: Pulling data for job 43
Update: Pulling data for job 44
Update: Pulling data for job 45
Update: Pulling data for job 46
Update: Pulling data for job 47
Update: Pulling data for job 48
Update: Pulling data for job 49
Update: Pulling data for job 50
Update: Pulling data for job 51
Update: Pulling data for job 52
Update: Pulling data for job 53
Update: Pulling data for job 54
Error: Error pulling data for job 54, executing attempt 2
Update: Pulling data for job 55
Update: Pulling data for job 56
Update: Pulling data for job 57
Error: Error pulling data for job 57, executing attempt 2
Update: Pulling data for job 58
Update: Pulling data for job 59
Update: Pulling data for job 60
Update: Pulling data for job 61
Update: Pulling data for job 62
Update: Pulling data for job 63
Update: Pulling data for job 64
Update: Pulling data for job 65
Update: Pulling data for job 66
Update: Pulling data for job 67
Update: Pulling data for job 68
Update: Pulling data for job 69
Update: Pulling data for job 70
Update: Pulling data for job 71
Update: Pulling data for job 72
Update: Pulling data for job 73
Update: Pulling data for job 74
Update: Pulling data for job 75
Update: Pulling data for job 76
Update: Pulling data for job 77
Update: Pulling data for job 78
Update: Pulling data for job 79
Update: Pulling data for job 80
Update: Pulling data for job 81
Update: Pulling data for job 82
Update: Pulling data for job 83
Error: Error pulling data for job 83, executing attempt 2
Update: Pulling data for job 84
Update: Pulling data for job 85
Update: Pulling data for job 86
Update: Pulling data for job 87
Update: Pulling data for job 88
Update: Pulling data for job 89
Update: Pulling data for job 90
Update: Pulling data for job 91
Update: Pulling data for job 92
Update: Pulling data for job 93
Update: Pulling data for job 94
Update: Pulling data for job 95
Update: Pulling data for job 96
Update: Pulling data for job 97
Update: Pulling data for job 98
Error: Error pulling data for job 98, executing attempt 2
Error: Error pulling data for job 98, executing attempt 3
Error: Error pulling data for job 98, ignoring row
Update: Pulling data for job 99
Update: Pulling data for job 100
Update: Pulling data for job 101
Error: Error pulling data for job 101, executing attempt 2
Error: Error pulling data for job 101, executing attempt 3
Error: Error pulling data for job 101, ignoring row
Update: Pulling data for job 102
Update: Pulling data for job 103
Update: Pulling data for job 104
Error: Error pulling data for job 104, executing attempt 2
Update: Pulling data for job 105
Update: Pulling data for job 106
Update: Pulling data for job 107
Update: Pulling data for job 108
Update: Pulling data for job 109
Update: Pulling data for job 110
Update: Pulling data for job 111
Update: Pulling data for job 112
Update: Pulling data for job 113
Update: Pulling data for job 114
Update: Pulling data for job 115
Update: Pulling data for job 116
Update: Pulling data for job 117
Update: Pulling data for job 118
Update: Pulling data for job 119
Error: Error pulling data for job 119, executing attempt 2
Error: Error pulling data for job 119, executing attempt 3
Error: Error pulling data for job 119, ignoring row
Update: Pulling data for job 120
Update: Pulling data for job 121
Update: Pulling data for job 122
Update: Pulling data for job 123
Update: Pulling data for job 124
Update: Pulling data for job 125
Update: Pulling data for job 126
Update: Pulling data for job 127
Error: Error pulling data for job 127, executing attempt 2
Update: Pulling data for job 128
Error: Error pulling data for job 128, executing attempt 2
Update: Pulling data for job 129
Update: Pulling data for job 130
Update: Pulling data for job 131
Update: Pulling data for job 132
Update: Pulling data for job 133
Update: Pulling data for job 134
Error: Error pulling data for job 134, executing attempt 2
Error: Error pulling data for job 134, executing attempt 3
Error: Error pulling data for job 134, ignoring row
Update: Pulling data for job 135
Update: Pulling data for job 136
Update: Pulling data for job 137
Update: Pulling data for job 138
Update: Pulling data for job 139
Update: Pulling data for job 140
Update: Pulling data for job 141
Update: Pulling data for job 142
Update: Pulling data for job 143
Update: Pulling data for job 144
Update: Pulling data for job 145
Update: Pulling data for job 146
Update: Pulling data for job 147
Update: Pulling data for job 148
Update: Pulling data for job 149
Update: Pulling data for job 150
Update: Pulling data for job 151
Update: Pulling data for job 152
Update: Pulling data for job 153
Update: Pulling data for job 154
Update: Pulling data for job 155
Update: Pulling data for job 156
Update: Pulling data for job 157
Update: Pulling data for job 158
Update: Pulling data for job 159
Update: Pulling data for job 160
Update: Pulling data for job 161
Update: Pulling data for job 162
Update: Pulling data for job 163
Update: Pulling data for job 164
Update: Pulling data for job 165
Update: Pulling data for job 166
Update: Pulling data for job 167
Update: Pulling data for job 168
Update: Pulling data for job 169
Update: Pulling data for job 170
Update: Pulling data for job 171
Update: Pulling data for job 172
Update: Pulling data for job 173
Error: Error pulling data for job 173, executing attempt 2
Update: Pulling data for job 174
Update: Pulling data for job 175
Update: Pulling data for job 176
Update: Pulling data for job 177
Update: Pulling data for job 178
Error: Error pulling data for job 178, executing attempt 2
Update: Pulling data for job 179
Update: Pulling data for job 180
Update: Pulling data for job 181
Update: Pulling data for job 182
Update: Pulling data for job 183
Update: Pulling data for job 184
Update: Pulling data for job 185
Update: Pulling data for job 186
Update: Pulling data for job 187
Update: Pulling data for job 188
Update: Pulling data for job 189
Update: Pulling data for job 190
Update: Pulling data for job 191
Update: Pulling data for job 192
Update: Pulling data for job 193
Update: Pulling data for job 194
Error: Error pulling data for job 194, executing attempt 2
Error: Error pulling data for job 194, executing attempt 3

Error: Error pulling data for job 194, ignoring row
Update: Pulling data for job 195
Update: Pulling data for job 196
Update: Pulling data for job 197
Error: Error pulling data for job 197, executing attempt 2
Error: Error pulling data for job 197, executing attempt 3
Error: Error pulling data for job 197, ignoring row
Update: Pulling data for job 198
Update: Pulling data for job 199
Update: Pulling data for job 200
Update: Pulling data for job 201
Error: Error pulling data for job 201, executing attempt 2
Error: Error pulling data for job 201, executing attempt 3
Error: Error pulling data for job 201, ignoring row
Update: Pulling data for job 202
Error: Error pulling data for job 202, executing attempt 2
Update: Pulling data for job 203
Update: Pulling data for job 204
Update: Pulling data for job 205
Error: Error pulling data for job 205, executing attempt 2
Error: Error pulling data for job 205, executing attempt 3
Error: Error pulling data for job 205, ignoring row
Update: Pulling data for job 206
Update: Pulling data for job 207
Error: Error pulling data for job 207, executing attempt 2
Error: Error pulling data for job 207, executing attempt 3
Error: Error pulling data for job 207, ignoring row
Update: Pulling data for job 208
Update: Pulling data for job 209
Update: Pulling data for job 210
Update: Pulling data for job 211
Update: Pulling data for job 212
Update: Pulling data for job 213
Update: Pulling data for job 214
Update: Pulling data for job 215
Update: Pulling data for job 216
Update: Pulling data for job 217
Update: Pulling data for job 218
Update: Pulling data for job 219
Update: Pulling data for job 220
Update: Pulling data for job 221
Error: Error pulling data for job 221, executing attempt 2
Update: Pulling data for job 222
Update: Pulling data for job 223
Update: Pulling data for job 224
Update: Pulling data for job 225
Update: Pulling data for job 226
Update: Pulling data for job 227
Update: Pulling data for job 228
Update: Pulling data for job 229
Update: Pulling data for job 230
Update: Pulling data for job 231
Update: Pulling data for job 232
Error: Error pulling data for job 232, executing attempt 2
Update: Pulling data for job 233
Update: Pulling data for job 234
Update: Pulling data for job 235
Update: Pulling data for job 236
Update: Pulling data for job 237
Update: Pulling data for job 238
Update: Pulling data for job 239
Update: Pulling data for job 240
Update: Pulling data for job 241
Update: Pulling data for job 242
Update: Pulling data for job 243
Update: Pulling data for job 244
Update: Pulling data for job 245
Error: Error pulling data for job 245, executing attempt 2
Update: Pulling data for job 246
Update: Pulling data for job 247
Update: Pulling data for job 248
Update: Pulling data for job 249
Update: Pulling data for job 250
Update: Pulling data for job 251
Update: Pulling data for job 252
Update: Pulling data for job 253
Update: Pulling data for job 254
Update: Pulling data for job 255
Update: Pulling data for job 256
Error: Error pulling data for job 256, executing attempt 2
Error: Error pulling data for job 256, executing attempt 3
Error: Error pulling data for job 256, ignoring row
Update: Pulling data for job 257
Update: Pulling data for job 258
Update: Pulling data for job 259
Error: Error pulling data for job 259, executing attempt 2
Error: Error pulling data for job 259, executing attempt 3
Error: Error pulling data for job 259, ignoring row
Update: Pulling data for job 260
Update: Pulling data for job 261
Update: Pulling data for job 262
Update: Pulling data for job 263
Update: Pulling data for job 264
Update: Pulling data for job 265
Error: Error pulling data for job 265, executing attempt 2
Update: Pulling data for job 266
Update: Pulling data for job 267
Update: Pulling data for job 268
Update: Pulling data for job 269
Update: Pulling data for job 270
Error: Error pulling data for job 270, executing attempt 2
Error: Error pulling data for job 270, executing attempt 3
Error: Error pulling data for job 270, ignoring row
Update: Pulling data for job 271
Update: Pulling data for job 272
Update: Pulling data for job 273
Update: Pulling data for job 274
Update: Pulling data for job 275
Update: Pulling data for job 276
Update: Pulling data for job 277
Error: Error pulling data for job 277, executing attempt 2
Update: Pulling data for job 278
Update: Pulling data for job 279
Update: Pulling data for job 280
Update: Pulling data for job 281
Update: Pulling data for job 282
Update: Pulling data for job 283
Update: Pulling data for job 284
Update: Pulling data for job 285
Update: Pulling data for job 286
Update: Pulling data for job 287
Update: Pulling data for job 288
Update: Pulling data for job 289
Update: Pulling data for job 290
Update: Pulling data for job 291
Update: Pulling data for job 292
Update: Pulling data for job 293
Update: Pulling data for job 294
Update: Pulling data for job 295
Update: Pulling data for job 296
Update: Pulling data for job 297
Update: Pulling data for job 298
Update: Pulling data for job 299
Update: Pulling data for job 300
Update: Pulling data for job 301
Update: Pulling data for job 302
Update: Pulling data for job 303
Update: Pulling data for job 304
Update: Pulling data for job 305
Update: Pulling data for job 306
Update: Pulling data for job 307
Update: Pulling data for job 308
Update: Pulling data for job 309
Update: Pulling data for job 310
Update: Pulling data for job 311
Update: Pulling data for job 312
Update: Pulling data for job 313
Update: Pulling data for job 314
Update: Pulling data for job 315
Update: Pulling data for job 316
Update: Pulling data for job 317
Update: Pulling data for job 318
Update: Pulling data for job 319
Error: Error pulling data for job 319, executing attempt 2
Update: Pulling data for job 320
Update: Pulling data for job 321
Update: Pulling data for job 322
Update: Pulling data for job 323
Error: Error pulling data for job 323, executing attempt 2
Update: Pulling data for job 324
Update: Pulling data for job 325
Update: Pulling data for job 326
Update: Pulling data for job 327
Update: Pulling data for job 328
Update: Pulling data for job 329
Update: Pulling data for job 330
Update: Pulling data for job 331
Update: Pulling data for job 332
Update: Pulling data for job 333
Error: Error pulling data for job 333, executing attempt 2
Update: Pulling data for job 334
Update: Pulling data for job 335
Update: Pulling data for job 336
Update: Pulling data for job 337
Update: Pulling data for job 338
Update: Pulling data for job 339
Update: Pulling data for job 340
Update: Pulling data for job 341
Update: Pulling data for job 342
Update: Pulling data for job 343
Update: Pulling data for job 344
Update: Pulling data for job 345
Update: Pulling data for job 346
Update: Pulling data for job 347
Update: Pulling data for job 348
Update: Pulling data for job 349
Update: Pulling data for job 350
Update: Pulling data for job 351
Update: Pulling data for job 352
Update: Pulling data for job 353
Update: Pulling data for job 354
Update: Pulling data for job 355
Update: Pulling data for job 356
Update: Pulling data for job 357
Error: Error pulling data for job 357, executing attempt 2
Error: Error pulling data for job 357, executing attempt 3
Error: Error pulling data for job 357, ignoring row
Update: Pulling data for job 358
Update: Pulling data for job 359
Update: Pulling data for job 360
Update: Pulling data for job 361
Update: Pulling data for job 362
Update: Pulling data for job 363
Update: Pulling data for job 364
Error: Error pulling data for job 364, executing attempt 2
Error: Error pulling data for job 364, executing attempt 3
Error: Error pulling data for job 364, ignoring row
Update: Pulling data for job 365
Update: Pulling data for job 366
Update: Pulling data for job 367
Update: Pulling data for job 368
Update: Pulling data for job 369
Update: Pulling data for job 370
Update: Pulling data for job 371
Update: Pulling data for job 372
Update: Pulling data for job 373
Update: Pulling data for job 374
Update: Pulling data for job 375
Update: Pulling data for job 376
Error: Error pulling data for job 376, executing attempt 2
Update: Pulling data for job 377

Update: Pulling data for job 378
Update: Pulling data for job 379
Update: Pulling data for job 380
Update: Pulling data for job 381
Update: Pulling data for job 382
Error: Error pulling data for job 382, executing attempt 2
Error: Error pulling data for job 382, executing attempt 3
Error: Error pulling data for job 382, ignoring row
Update: Pulling data for job 383
Update: Pulling data for job 384
Error: Error pulling data for job 384, executing attempt 2
Error: Error pulling data for job 384, executing attempt 3
Error: Error pulling data for job 384, ignoring row
Update: Pulling data for job 385
Update: Pulling data for job 386
Update: Pulling data for job 387
Update: Pulling data for job 388
Update: Pulling data for job 389
Update: Pulling data for job 390
Update: Pulling data for job 391
Update: Pulling data for job 392
Update: Pulling data for job 393
Update: Pulling data for job 394
Update: Pulling data for job 395
Update: Pulling data for job 396
Update: Pulling data for job 397
Update: Pulling data for job 398
Update: Pulling data for job 399
Update: Pulling data for job 400
Update: Pulling data for job 401
Update: Pulling data for job 402
Update: Pulling data for job 403
Update: Pulling data for job 404
Update: Pulling data for job 405
Update: Pulling data for job 406
Error: Error pulling data for job 406, executing attempt 2
Error: Error pulling data for job 406, executing attempt 3
Error: Error pulling data for job 406, ignoring row
Update: Pulling data for job 407
Update: Pulling data for job 408
Update: Pulling data for job 409
Update: Pulling data for job 410
Update: Pulling data for job 411
Update: Pulling data for job 412
Update: Pulling data for job 413
Update: Pulling data for job 414
Update: Pulling data for job 415
Update: Pulling data for job 416
Update: Pulling data for job 417
Update: Pulling data for job 418
Update: Pulling data for job 419
Update: Pulling data for job 420
Update: Pulling data for job 421
Update: Pulling data for job 422
Update: Pulling data for job 423
Update: Pulling data for job 424
Update: Pulling data for job 425
Update: Pulling data for job 426
Error: Error pulling data for job 426, executing attempt 2
Error: Error pulling data for job 426, executing attempt 3
Error: Error pulling data for job 426, ignoring row
Update: Pulling data for job 427
Update: Pulling data for job 428
Update: Pulling data for job 429
Update: Pulling data for job 430
Update: Pulling data for job 431
Update: Pulling data for job 432
Update: Pulling data for job 433
Update: Pulling data for job 434
Update: Pulling data for job 435
Update: Pulling data for job 436
Error: Error pulling data for job 436, executing attempt 2
Update: Pulling data for job 437
Update: Pulling data for job 438
Error: Error pulling data for job 438, executing attempt 2
Error: Error pulling data for job 438, executing attempt 3
Error: Error pulling data for job 438, ignoring row
Update: Pulling data for job 439
Update: Pulling data for job 440
Update: Pulling data for job 441
Update: Pulling data for job 442
Update: Pulling data for job 443
Update: Pulling data for job 444
Update: Pulling data for job 445
Update: Pulling data for job 446
Update: Pulling data for job 447
Update: Pulling data for job 448
Update: Pulling data for job 449
Update: Pulling data for job 450
Update: Pulling data for job 451
Error: Error pulling data for job 451, executing attempt 2
Error: Error pulling data for job 451, executing attempt 3
Error: Error pulling data for job 451, ignoring row
Update: Pulling data for job 452
Update: Pulling data for job 453
Update: Pulling data for job 454
Update: Pulling data for job 455
Update: Pulling data for job 456
Update: Pulling data for job 457
Update: Pulling data for job 458
Update: Pulling data for job 459
Update: Pulling data for job 460
Update: Pulling data for job 461
Update: Pulling data for job 462
Update: Pulling data for job 463
Update: Pulling data for job 464
Update: Pulling data for job 465
Update: Pulling data for job 466
Update: Pulling data for job 467
Update: Pulling data for job 468
Error: Error pulling data for job 468, executing attempt 2
Update: Pulling data for job 469
Update: Pulling data for job 470
Update: Pulling data for job 471
Update: Pulling data for job 472
Update: Pulling data for job 473
Update: Pulling data for job 474
Update: Pulling data for job 475
Error: Error pulling data for job 475, executing attempt 2
Update: Pulling data for job 476
Update: Pulling data for job 477
Update: Pulling data for job 478
Update: Pulling data for job 479
Update: Pulling data for job 480
Update: Pulling data for job 481
Update: Pulling data for job 482
Error: Error pulling data for job 482, executing attempt 2
Update: Pulling data for job 483
Update: Pulling data for job 484
Update: Pulling data for job 485
Update: Pulling data for job 486
Update: Pulling data for job 487
Update: Pulling data for job 488
Update: Pulling data for job 489
Update: Pulling data for job 490
Update: Pulling data for job 491
Update: Pulling data for job 492
Update: Pulling data for job 493
Update: Pulling data for job 494
Update: Pulling data for job 495
Update: Pulling data for job 496
Update: Pulling data for job 497
Update: Pulling data for job 498
Update: Pulling data for job 499
Update: Pulling data for job 500
Update: Pulling data for job 501
Update: Pulling data for job 502
Update: Pulling data for job 503
Update: Pulling data for job 504
Error: Error pulling data for job 504, executing attempt 2
Update: Pulling data for job 505
Update: Pulling data for job 506
Update: Pulling data for job 507
Update: Pulling data for job 508
Update: Pulling data for job 509
Update: Pulling data for job 510
Update: Pulling data for job 511
Update: Pulling data for job 512
Update: Pulling data for job 513
Error: Error pulling data for job 513, executing attempt 2
Update: Pulling data for job 514
Update: Pulling data for job 515
Update: Pulling data for job 516
Update: Pulling data for job 517
Update: Pulling data for job 518
Update: Pulling data for job 519
Update: Pulling data for job 520
Update: Pulling data for job 521
Update: Pulling data for job 522
Update: Pulling data for job 523
Update: Pulling data for job 524
Update: Pulling data for job 525
Error: Error pulling data for job 525, executing attempt 2
Update: Pulling data for job 526
Update: Pulling data for job 527
Update: Pulling data for job 528
Update: Pulling data for job 529
Update: Pulling data for job 530
Update: Pulling data for job 531
Error: Error pulling data for job 531, executing attempt 2
Update: Pulling data for job 532
Update: Pulling data for job 533
Update: Pulling data for job 534
Update: Pulling data for job 535
Update: Pulling data for job 536
Update: Pulling data for job 537
Update: Pulling data for job 538
Update: Pulling data for job 539
Update: Pulling data for job 540
Update: Pulling data for job 541
Update: Pulling data for job 542
Update: Pulling data for job 543
Update: Pulling data for job 544
Error: Error pulling data for job 544, executing attempt 2
Update: Pulling data for job 545
Update: Pulling data for job 546
Update: Pulling data for job 547
Update: Pulling data for job 548
Update: Pulling data for job 549
Update: Pulling data for job 550
Update: Pulling data for job 551
Update: Pulling data for job 552
Update: Pulling data for job 553
Update: Pulling data for job 554
Update: Pulling data for job 555
Update: Pulling data for job 556
Update: Pulling data for job 557
Update: Pulling data for job 558
Update: Pulling data for job 559
Update: Pulling data for job 560
Update: Pulling data for job 561
Update: Pulling data for job 562
Update: Pulling data for job 563
Update: Pulling data for job 564
Update: Pulling data for job 565
Update: Pulling data for job 566
Update: Pulling data for job 567
Update: Pulling data for job 568
Update: Pulling data for job 569
Update: Pulling data for job 570
Update: Pulling data for job 571
Update: Pulling data for job 572
Update: Pulling data for job 573
Update: Pulling data for job 574
Update: Pulling data for job 575
Update: Pulling data for job 576
Update: Pulling data for job 577
Update: Pulling data for job 578
Update: Pulling data for job 579

Update: Pulling data for job 580
Update: Pulling data for job 581
Update: Pulling data for job 582
Update: Pulling data for job 583
Update: Pulling data for job 584
Update: Pulling data for job 585
Update: Pulling data for job 586
Update: Pulling data for job 587
Update: Pulling data for job 588
Update: Pulling data for job 589
Update: Pulling data for job 590
Update: Pulling data for job 591
Update: Pulling data for job 592
Update: Pulling data for job 593
Error: Error pulling data for job 593, executing attempt 2
Error: Error pulling data for job 593, executing attempt 3
Error: Error pulling data for job 593, ignoring row
Update: Pulling data for job 594
Update: Pulling data for job 595
Update: Pulling data for job 596
Update: Pulling data for job 597
Update: Pulling data for job 598
Update: Pulling data for job 599
Update: Pulling data for job 600
Update: Pulling data for job 601
Error: Error pulling data for job 601, executing attempt 2
Update: Pulling data for job 602
Update: Pulling data for job 603
Update: Pulling data for job 604
Update: Pulling data for job 605
Error: Error pulling data for job 605, executing attempt 2
Update: Pulling data for job 606
Update: Pulling data for job 607
Update: Pulling data for job 608
Update: Pulling data for job 609
Update: Pulling data for job 610
Update: Pulling data for job 611
Update: Pulling data for job 612
Update: Pulling data for job 613
Update: Pulling data for job 614
Update: Pulling data for job 615
Update: Pulling data for job 616
Update: Pulling data for job 617
Update: Pulling data for job 618
Update: Pulling data for job 619
Error: Error pulling data for job 619, executing attempt 2
Update: Pulling data for job 620
Update: Pulling data for job 621
Update: Pulling data for job 622
Update: Pulling data for job 623
Update: Pulling data for job 624
Update: Pulling data for job 625
Update: Pulling data for job 626
Error: Error pulling data for job 626, executing attempt 2
Error: Error pulling data for job 626, executing attempt 3
Error: Error pulling data for job 626, ignoring row
Update: Pulling data for job 627
Update: Pulling data for job 628
Update: Pulling data for job 629
Update: Pulling data for job 630
Update: Pulling data for job 631
Update: Pulling data for job 632
Update: Pulling data for job 633
Update: Pulling data for job 634
Update: Pulling data for job 635
Update: Pulling data for job 636
Update: Pulling data for job 637
Update: Pulling data for job 638
Update: Pulling data for job 639
Update: Pulling data for job 640
Update: Pulling data for job 641
Update: Pulling data for job 642
Update: Pulling data for job 643
Update: Pulling data for job 644
Update: Pulling data for job 645
Update: Pulling data for job 646
Update: Pulling data for job 647
Update: Pulling data for job 648
Update: Pulling data for job 649
Update: Pulling data for job 650
Update: Pulling data for job 651
Update: Pulling data for job 652
Update: Pulling data for job 653
Update: Pulling data for job 654
Update: Pulling data for job 655
Update: Pulling data for job 656
Update: Pulling data for job 657
Update: Pulling data for job 658
Update: Pulling data for job 659
Update: Pulling data for job 660
Update: Pulling data for job 661
Update: Pulling data for job 662
Update: Pulling data for job 663
Update: Pulling data for job 664
Update: Pulling data for job 665
Update: Pulling data for job 666
Update: Pulling data for job 667
Error: Error pulling data for job 667, executing attempt 2
Error: Error pulling data for job 667, executing attempt 3
Error: Error pulling data for job 667, ignoring row
Update: Pulling data for job 668
Update: Pulling data for job 669
Update: Pulling data for job 670
Update: Pulling data for job 671
Error: Error pulling data for job 671, executing attempt 2
Error: Error pulling data for job 671, executing attempt 3
Error: Error pulling data for job 671, ignoring row
Update: Pulling data for job 672
Error: Error pulling data for job 672, executing attempt 2
Error: Error pulling data for job 672, executing attempt 3
Error: Error pulling data for job 672, ignoring row
Update: Pulling data for job 673
Update: Pulling data for job 674
Update: Pulling data for job 675
Error: Error pulling data for job 675, executing attempt 2
Error: Error pulling data for job 675, executing attempt 3
Error: Error pulling data for job 675, ignoring row
Update: Pulling data for job 676
Update: Pulling data for job 677
Update: Pulling data for job 678
Update: Pulling data for job 679
Update: Pulling data for job 680
Error: Error pulling data for job 680, executing attempt 2
Error: Error pulling data for job 680, executing attempt 3
Error: Error pulling data for job 680, ignoring row
Update: Pulling data for job 681
Update: Pulling data for job 682
Update: Pulling data for job 683
Error: Error pulling data for job 683, executing attempt 2
Update: Pulling data for job 684
Update: Pulling data for job 685
Update: Pulling data for job 686
Error: Error pulling data for job 686, executing attempt 2
Error: Error pulling data for job 686, executing attempt 3
Error: Error pulling data for job 686, ignoring row
Update: Pulling data for job 687
Error: Error pulling data for job 687, executing attempt 2
Error: Error pulling data for job 687, executing attempt 3
Error: Error pulling data for job 687, ignoring row
Update: Pulling data for job 688
Error: Error pulling data for job 688, executing attempt 2
Error: Error pulling data for job 688, executing attempt 3
Error: Error pulling data for job 688, ignoring row
Update: Pulling data for job 689
Update: Pulling data for job 690
Error: Error pulling data for job 690, executing attempt 2
Error: Error pulling data for job 690, executing attempt 3
Error: Error pulling data for job 690, ignoring row
Update: Pulling data for job 691
Error: Error pulling data for job 691, executing attempt 2
Error: Error pulling data for job 691, executing attempt 3
Error: Error pulling data for job 691, ignoring row
Update: Pulling data for job 692
Error: Error pulling data for job 692, executing attempt 2
Error: Error pulling data for job 692, executing attempt 3
Error: Error pulling data for job 692, ignoring row
Update: Pulling data for job 693
Error: Error pulling data for job 693, executing attempt 2
Error: Error pulling data for job 693, executing attempt 3
Error: Error pulling data for job 693, ignoring row
Update: Pulling data for job 694
Update: Pulling data for job 695
Update: Pulling data for job 696
Update: Pulling data for job 697
Update: Pulling data for job 698
Update: Pulling data for job 699
Update: Pulling data for job 700
Update: Pulling data for job 701
Update: Pulling data for job 702
Update: Pulling data for job 703
Update: Pulling data for job 704
Update: Pulling data for job 705
Update: Pulling data for job 706
Update: Pulling data for job 707
Update: Pulling data for job 708
Update: Pulling data for job 709
Update: Pulling data for job 710
Error: Error pulling data for job 710, executing attempt 2
Update: Pulling data for job 711
Update: Pulling data for job 712
Update: Pulling data for job 713
Update: Pulling data for job 714
Update: Pulling data for job 715
Update: Pulling data for job 716
Update: Pulling data for job 717
Update: Pulling data for job 718
Update: Pulling data for job 719
Update: Pulling data for job 720
Update: Pulling data for job 721
Update: Pulling data for job 722
Update: Pulling data for job 723
Update: Pulling data for job 724
Update: Pulling data for job 725
Update: Pulling data for job 726
Update: Pulling data for job 727
Update: Pulling data for job 728
Update: Pulling data for job 729
Update: Pulling data for job 730
Update: Pulling data for job 731
Update: Pulling data for job 732
Update: Pulling data for job 733
Update: Pulling data for job 734
Update: Pulling data for job 735
Update: Pulling data for job 736
Update: Pulling data for job 737
Update: Pulling data for job 738
Update: Pulling data for job 739
Update: Pulling data for job 740
Update: Pulling data for job 741
Update: Pulling data for job 742
Update: Pulling data for job 743
Update: Pulling data for job 744
Update: Pulling data for job 745
Update: Pulling data for job 746
Update: Pulling data for job 747

Update: Pulling data for job 748
Update: Pulling data for job 749
Error: Error pulling data for job 749, executing attempt 2
Update: Pulling data for job 750
Update: Pulling data for job 751
Update: Pulling data for job 752
Update: Pulling data for job 753
Update: Pulling data for job 754
Update: Pulling data for job 755
Update: Pulling data for job 756
Update: Pulling data for job 757
Update: Pulling data for job 758
Update: Pulling data for job 759
Update: Pulling data for job 760
Error: Error pulling data for job 760, executing attempt 2
Update: Pulling data for job 761
Update: Pulling data for job 762
Update: Pulling data for job 763
Update: Pulling data for job 764
Update: Pulling data for job 765
Update: Pulling data for job 766
Update: Pulling data for job 767
Update: Pulling data for job 768
Update: Pulling data for job 769
Update: Pulling data for job 770
Update: Pulling data for job 771
Update: Pulling data for job 772
Update: Pulling data for job 773
Update: Pulling data for job 774
Update: Pulling data for job 775
Update: Pulling data for job 776
Update: Pulling data for job 777
Update: Pulling data for job 778
Update: Pulling data for job 779
Update: Pulling data for job 780
Update: Pulling data for job 781
Update: Pulling data for job 782
Update: Pulling data for job 783
Update: Pulling data for job 784
Update: Pulling data for job 785
Update: Pulling data for job 786
Update: Pulling data for job 787
Update: Pulling data for job 788
Update: Pulling data for job 789
Update: Pulling data for job 790
Error: Error pulling data for job 790, executing attempt 2
Update: Pulling data for job 791
Update: Pulling data for job 792
Update: Pulling data for job 793
Update: Pulling data for job 794
Update: Pulling data for job 795
Update: Pulling data for job 796
Update: Pulling data for job 797
Update: Pulling data for job 798
Error: Error pulling data for job 798, executing attempt 2
Update: Pulling data for job 799
Update: Pulling data for job 800
Update: Pulling data for job 801
Update: Pulling data for job 802
Update: Pulling data for job 803
Update: Pulling data for job 804
Update: Pulling data for job 805
Update: Pulling data for job 806
Update: Pulling data for job 807
Update: Pulling data for job 808
Error: Error pulling data for job 808, executing attempt 2
Error: Error pulling data for job 808, executing attempt 3
Error: Error pulling data for job 808, ignoring row
Update: Pulling data for job 809
Update: Pulling data for job 810
Update: Pulling data for job 811
Update: Pulling data for job 812
Update: Pulling data for job 813
Update: Pulling data for job 814
Update: Pulling data for job 815
Update: Pulling data for job 816
Update: Pulling data for job 817
Update: Pulling data for job 818
Update: Pulling data for job 819
Update: Pulling data for job 820
Update: Pulling data for job 821
Update: Pulling data for job 822
Update: Pulling data for job 823
Update: Pulling data for job 824
Update: Pulling data for job 825
Update: Pulling data for job 826
Update: Pulling data for job 827
Update: Pulling data for job 828
Update: Pulling data for job 829
Error: Error pulling data for job 829, executing attempt 2
Error: Error pulling data for job 829, executing attempt 3
Error: Error pulling data for job 829, ignoring row
Update: Pulling data for job 830
Update: Pulling data for job 831
Update: Pulling data for job 832
Update: Pulling data for job 833
Update: Pulling data for job 834
Update: Pulling data for job 835
Update: Pulling data for job 836
Update: Pulling data for job 837
Update: Pulling data for job 838
Update: Pulling data for job 839
Update: Pulling data for job 840
Update: Pulling data for job 841
Update: Pulling data for job 842
Update: Pulling data for job 843
Update: Pulling data for job 844
Update: Pulling data for job 845
Error: Error pulling data for job 845, executing attempt 2
Update: Pulling data for job 846
Update: Pulling data for job 847
Update: Pulling data for job 848
Update: Pulling data for job 849
Update: Pulling data for job 850
Update: Pulling data for job 851
Update: Pulling data for job 852
Update: Pulling data for job 853
Update: Pulling data for job 854
Update: Pulling data for job 855
Error: Error pulling data for job 855, executing attempt 2
Update: Pulling data for job 856
Update: Pulling data for job 857
Update: Pulling data for job 858
Update: Pulling data for job 859
Error: Error pulling data for job 859, executing attempt 2
Update: Pulling data for job 860
Error: Error pulling data for job 860, executing attempt 2
Update: Pulling data for job 861
Update: Pulling data for job 862
Update: Pulling data for job 863
Update: Pulling data for job 864
Update: Pulling data for job 865
Update: Pulling data for job 866
Update: Pulling data for job 867
Update: Pulling data for job 868
Update: Pulling data for job 869
Update: Pulling data for job 870
Update: Pulling data for job 871
Update: Pulling data for job 872
Update: Pulling data for job 873
Update: Pulling data for job 874
Error: Error pulling data for job 874, executing attempt 2
Update: Pulling data for job 875
Update: Pulling data for job 876
Update: Pulling data for job 877
Update: Pulling data for job 878
Update: Pulling data for job 879
Update: Pulling data for job 880
Update: Pulling data for job 881
Update: Pulling data for job 882
Update: Pulling data for job 883
Update: Pulling data for job 884
Update: Pulling data for job 885
Update: Pulling data for job 886
Update: Pulling data for job 887
Update: Pulling data for job 888
Update: Pulling data for job 889
Update: Pulling data for job 890
Update: Pulling data for job 891
Update: Pulling data for job 892
Update: Pulling data for job 893
Update: Pulling data for job 894
Update: Pulling data for job 895
Update: Pulling data for job 896
Error: Error pulling data for job 896, executing attempt 2
Update: Pulling data for job 897
Update: Pulling data for job 898
Update: Pulling data for job 899
Update: Pulling data for job 900
Update: Pulling data for job 901
Error: Error pulling data for job 901, executing attempt 2
Update: Pulling data for job 902
Update: Pulling data for job 903
Update: Pulling data for job 904
Update: Pulling data for job 905
Update: Pulling data for job 906
Update: Pulling data for job 907
Update: Pulling data for job 908
Error: Error pulling data for job 908, executing attempt 2
Update: Pulling data for job 909
Update: Pulling data for job 910
Update: Pulling data for job 911
Update: Pulling data for job 912
Update: Pulling data for job 913
Update: Pulling data for job 914
Update: Pulling data for job 915
Update: Pulling data for job 916
Update: Pulling data for job 917
Update: Pulling data for job 918
Update: Pulling data for job 919
Update: Pulling data for job 920
Update: Pulling data for job 921
Update: Pulling data for job 922
Update: Pulling data for job 923
Update: Pulling data for job 924
Update: Pulling data for job 925
Update: Pulling data for job 926
Update: Pulling data for job 927
Update: Pulling data for job 928
Update: Pulling data for job 929
Update: Pulling data for job 930
Update: Pulling data for job 931
Update: Pulling data for job 932
Update: Pulling data for job 933
Update: Pulling data for job 934
Update: Pulling data for job 935
Error: Error pulling data for job 935, executing attempt 2
Error: Error pulling data for job 935, executing attempt 3
Error: Error pulling data for job 935, ignoring row
Update: Pulling data for job 936
Update: Pulling data for job 937
Update: Pulling data for job 938
Update: Pulling data for job 939
Update: Pulling data for job 940
Error: Error pulling data for job 940, executing attempt 2
Error: Error pulling data for job 940, executing attempt 3
Error: Error pulling data for job 940, ignoring row
Update: Pulling data for job 941
Error: Error pulling data for job 941, executing attempt 2
Error: Error pulling data for job 941, executing attempt 3
Error: Error pulling data for job 941, ignoring row
Update: Pulling data for job 942
Update: Pulling data for job 943
Update: Pulling data for job 944
Update: Pulling data for job 945
Update: Pulling data for job 946
Update: Pulling data for job 947
Update: Pulling data for job 948
Update: Pulling data for job 949

Update: Pulling data for job 950
Update: Pulling data for job 951
Update: Pulling data for job 952
Update: Pulling data for job 953
Update: Pulling data for job 954
Update: Pulling data for job 955
Update: Pulling data for job 956
Update: Pulling data for job 957
Error: Error pulling data for job 957, executing attempt 2
Update: Pulling data for job 958
Update: Pulling data for job 959
Update: Pulling data for job 960
Update: Pulling data for job 961
Update: Pulling data for job 962
Update: Pulling data for job 963
Update: Pulling data for job 964
Update: Pulling data for job 965
Update: Pulling data for job 966
Update: Pulling data for job 967
Update: Pulling data for job 968
Update: Pulling data for job 969
Update: Pulling data for job 970
Update: Pulling data for job 971
Update: Pulling data for job 972
Update: Pulling data for job 973
Update: Pulling data for job 974
Update: Pulling data for job 975
Update: Pulling data for job 976
Update: Pulling data for job 977
Update: Pulling data for job 978
Update: Pulling data for job 979
Update: Pulling data for job 980
Error: Error pulling data for job 980, executing attempt 2
Update: Pulling data for job 981
Update: Pulling data for job 982
Update: Pulling data for job 983
Update: Pulling data for job 984
Update: Pulling data for job 985
Update: Pulling data for job 986
Update: Pulling data for job 987
Update: Pulling data for job 988
Update: Pulling data for job 989
Update: Pulling data for job 990
Update: Pulling data for job 991
Update: Pulling data for job 992
Update: Pulling data for job 993
Update: Pulling data for job 994
Update: Pulling data for job 995
Update: Pulling data for job 996
Update: Pulling data for job 997
Update: Pulling data for job 998
Update: Pulling data for job 999
Update: Pulling data for job 1000
Update: Pulling data for job 1001
Error: Error pulling data for job 1001, executing attempt 2
Update: Pulling data for job 1002
Update: Pulling data for job 1003
Update: Pulling data for job 1004
Update: Pulling data for job 1005
Update: Pulling data for job 1006
Error: Error pulling data for job 1006, executing attempt 2
Error: Error pulling data for job 1006, executing attempt 3
Error: Error pulling data for job 1006, ignoring row
Update: Pulling data for job 1007
Update: Pulling data for job 1008
Update: Pulling data for job 1009
Update: Pulling data for job 1010
Update: Pulling data for job 1011
Update: Pulling data for job 1012
Update: Pulling data for job 1013
Update: Pulling data for job 1014
Update: Pulling data for job 1015
Update: Pulling data for job 1016
Update: Pulling data for job 1017
Error: Error pulling data for job 1017, executing attempt 2
Error: Error pulling data for job 1017, executing attempt 3
Error: Error pulling data for job 1017, ignoring row
Update: Pulling data for job 1018
Update: Pulling data for job 1019
Update: Pulling data for job 1020
Update: Pulling data for job 1021
Update: Pulling data for job 1022
Update: Pulling data for job 1023
Update: Pulling data for job 1024
Update: Pulling data for job 1025
Update: Pulling data for job 1026
Update: Pulling data for job 1027
Update: Pulling data for job 1028
Update: Pulling data for job 1029
Update: Pulling data for job 1030
Update: Pulling data for job 1031
Update: Pulling data for job 1032
Update: Pulling data for job 1033
Update: Pulling data for job 1034
Update: Pulling data for job 1035
Update: Pulling data for job 1036
Update: Pulling data for job 1037
Update: Pulling data for job 1038
Update: Pulling data for job 1039
Update: Pulling data for job 1040
Update: Pulling data for job 1041
Error: Error pulling data for job 1041, executing attempt 2
Error: Error pulling data for job 1041, executing attempt 3
Error: Error pulling data for job 1041, ignoring row
Update: Pulling data for job 1042
Update: Pulling data for job 1043
Update: Pulling data for job 1044
Update: Pulling data for job 1045
Error: Error pulling data for job 1045, executing attempt 2
Error: Error pulling data for job 1045, executing attempt 3
Error: Error pulling data for job 1045, ignoring row
Update: Pulling data for job 1046
Update: Pulling data for job 1047
Update: Pulling data for job 1048
Update: Pulling data for job 1049
Update: Pulling data for job 1050
Update: Pulling data for job 1051
Update: Pulling data for job 1052
Update: Pulling data for job 1053
Update: Pulling data for job 1054
Error: Error pulling data for job 1054, executing attempt 2
Update: Pulling data for job 1055
Update: Pulling data for job 1056
Error: Error pulling data for job 1056, executing attempt 2
Update: Pulling data for job 1057
Update: Pulling data for job 1058
Update: Pulling data for job 1059
Update: Pulling data for job 1060
Error: Error pulling data for job 1060, executing attempt 2
Update: Pulling data for job 1061
Update: Pulling data for job 1062
Update: Pulling data for job 1063
Update: Pulling data for job 1064
Update: Pulling data for job 1065
Update: Pulling data for job 1066
Update: Pulling data for job 1067
Error: Error pulling data for job 1067, executing attempt 2
Update: Pulling data for job 1068
Update: Pulling data for job 1069
Update: Pulling data for job 1070
Update: Pulling data for job 1071
Update: Pulling data for job 1072
Update: Pulling data for job 1073
Update: Pulling data for job 1074
Update: Pulling data for job 1075
Update: Pulling data for job 1076
Update: Pulling data for job 1077
Update: Pulling data for job 1078
Update: Pulling data for job 1079
Update: Pulling data for job 1080
Update: Pulling data for job 1081
Update: Pulling data for job 1082
Update: Pulling data for job 1083
Update: Pulling data for job 1084
Update: Pulling data for job 1085
Update: Pulling data for job 1086
Update: Pulling data for job 1087
Update: Pulling data for job 1088
Update: Pulling data for job 1089
Update: Pulling data for job 1090
Update: Pulling data for job 1091
Update: Pulling data for job 1092
Update: Pulling data for job 1093
Update: Pulling data for job 1094
Error: Error pulling data for job 1094, executing attempt 2
Update: Pulling data for job 1095
Update: Pulling data for job 1096
Update: Pulling data for job 1097
Update: Pulling data for job 1098
Update: Pulling data for job 1099
Update: Pulling data for job 1100
Update: Pulling data for job 1101
Update: Pulling data for job 1102
Update: Pulling data for job 1103
Update: Pulling data for job 1104
Update: Pulling data for job 1105
Update: Pulling data for job 1106
Update: Pulling data for job 1107
Update: Pulling data for job 1108
Update: Pulling data for job 1109
Update: Pulling data for job 1110
Update: Pulling data for job 1111
Update: Pulling data for job 1112
Update: Pulling data for job 1113
Update: Pulling data for job 1114
Update: Pulling data for job 1115
Update: Pulling data for job 1116
Update: Pulling data for job 1117
Update: Pulling data for job 1118
Update: Pulling data for job 1119
Update: Pulling data for job 1120
Update: Pulling data for job 1121
Error: Error pulling data for job 1121, executing attempt 2
Update: Pulling data for job 1122
Update: Pulling data for job 1123
Update: Pulling data for job 1124
Update: Pulling data for job 1125
Update: Pulling data for job 1126
Update: Pulling data for job 1127
Update: Pulling data for job 1128
Update: Pulling data for job 1129
Update: Pulling data for job 1130
Update: Pulling data for job 1131
Update: Pulling data for job 1132
Update: Pulling data for job 1133
Update: Pulling data for job 1134
Update: Pulling data for job 1135
Update: Pulling data for job 1136
Update: Pulling data for job 1137
Update: Pulling data for job 1138
Update: Pulling data for job 1139
Update: Pulling data for job 1140
Update: Pulling data for job 1141
Update: Pulling data for job 1142
Update: Pulling data for job 1143
Update: Pulling data for job 1144
Update: Pulling data for job 1145
Update: Pulling data for job 1146
Update: Pulling data for job 1147
Update: Pulling data for job 1148
Update: Pulling data for job 1149
Update: Pulling data for job 1150
Update: Pulling data for job 1151
Update: Pulling data for job 1152
Update: Pulling data for job 1153
Update: Pulling data for job 1154
Update: Pulling data for job 1155
Update: Pulling data for job 1156

Update: Pulling data for job 1157
Update: Pulling data for job 1158
Update: Pulling data for job 1159
Update: Pulling data for job 1160
Update: Pulling data for job 1161
Update: Pulling data for job 1162
Update: Pulling data for job 1163
Update: Pulling data for job 1164
Update: Pulling data for job 1165
Update: Pulling data for job 1166
Update: Pulling data for job 1167
Update: Pulling data for job 1168
Update: Pulling data for job 1169
Update: Pulling data for job 1170
Update: Pulling data for job 1171
Update: Pulling data for job 1172
Update: Pulling data for job 1173
Update: Pulling data for job 1174
Update: Pulling data for job 1175
Update: Pulling data for job 1176
Update: Pulling data for job 1177
Update: Pulling data for job 1178
Update: Pulling data for job 1179
Update: Pulling data for job 1180
Update: Pulling data for job 1181
Update: Pulling data for job 1182
Update: Pulling data for job 1183
Update: Pulling data for job 1184
Update: Pulling data for job 1185
Error: Error pulling data for job 1185, executing attempt 2
Update: Pulling data for job 1186
Update: Pulling data for job 1187
Update: Pulling data for job 1188
Update: Pulling data for job 1189
Update: Pulling data for job 1190
Update: Pulling data for job 1191
Update: Pulling data for job 1192
Update: Pulling data for job 1193
Update: Pulling data for job 1194
Update: Pulling data for job 1195
Update: Pulling data for job 1196
Update: Pulling data for job 1197
Update: Pulling data for job 1198
Update: Pulling data for job 1199
Update: Pulling data for job 1200
Update: Pulling data for job 1201
Update: Pulling data for job 1202
Update: Pulling data for job 1203
Update: Pulling data for job 1204
Update: Pulling data for job 1205
Update: Pulling data for job 1206
Update: Pulling data for job 1207
Update: Pulling data for job 1208
Update: Pulling data for job 1209
Error: Error pulling data for job 1209, executing attempt 2
Error: Error pulling data for job 1209, executing attempt 3
Error: Error pulling data for job 1209, ignoring row
Update: Pulling data for job 1210
Update: Pulling data for job 1211
Update: Pulling data for job 1212
Update: Pulling data for job 1213
Update: Pulling data for job 1214
Update: Pulling data for job 1215
Update: Pulling data for job 1216
Update: Pulling data for job 1217
Update: Pulling data for job 1218
Update: Pulling data for job 1219
Update: Pulling data for job 1220
Update: Pulling data for job 1221
Update: Pulling data for job 1222
Update: Pulling data for job 1223
Update: Pulling data for job 1224
Update: Pulling data for job 1225
Update: Pulling data for job 1226
Error: Error pulling data for job 1226, executing attempt 2
Update: Pulling data for job 1227
Update: Pulling data for job 1228
Update: Pulling data for job 1229
Update: Pulling data for job 1230
Update: Pulling data for job 1231
Update: Pulling data for job 1232
Update: Pulling data for job 1233
Update: Pulling data for job 1234
Update: Pulling data for job 1235
Update: Pulling data for job 1236
Update: Pulling data for job 1237
Update: Pulling data for job 1238
Update: Pulling data for job 1239
Update: Pulling data for job 1240
Update: Pulling data for job 1241
Update: Pulling data for job 1242
Update: Pulling data for job 1243
Update: Pulling data for job 1244
Error: Error pulling data for job 1244, executing attempt 2
Error: Error pulling data for job 1244, executing attempt 3
Error: Error pulling data for job 1244, ignoring row
Update: Pulling data for job 1245
Update: Pulling data for job 1246
Update: Pulling data for job 1247
Error: Error pulling data for job 1247, executing attempt 2
Error: Error pulling data for job 1247, executing attempt 3
Error: Error pulling data for job 1247, ignoring row
Update: Pulling data for job 1248
Error: Error pulling data for job 1248, executing attempt 2
Update: Pulling data for job 1249
Update: Pulling data for job 1250
Update: Pulling data for job 1251
Update: Pulling data for job 1252
Update: Pulling data for job 1253
Update: Pulling data for job 1254
Update: Pulling data for job 1255
Update: Pulling data for job 1256
Update: Pulling data for job 1257
Update: Pulling data for job 1258
Update: Pulling data for job 1259
Update: Pulling data for job 1260
Update: Pulling data for job 1261
Update: Pulling data for job 1262
Update: Pulling data for job 1263
Update: Pulling data for job 1264
Update: Pulling data for job 1265
Update: Pulling data for job 1266
Update: Pulling data for job 1267
Update: Pulling data for job 1268
Update: Pulling data for job 1269
Update: Pulling data for job 1270
Update: Pulling data for job 1271
Update: Pulling data for job 1272
Update: Pulling data for job 1273
Update: Pulling data for job 1274
Update: Pulling data for job 1275
Update: Pulling data for job 1276
Update: Pulling data for job 1277
Update: Pulling data for job 1278
Update: Pulling data for job 1279
Update: Pulling data for job 1280
Update: Pulling data for job 1281
Update: Pulling data for job 1282
Update: Pulling data for job 1283
Update: Pulling data for job 1284
Update: Pulling data for job 1285
Update: Pulling data for job 1286
Error: Error pulling data for job 1286, executing attempt 2
Error: Error pulling data for job 1286, executing attempt 3
Error: Error pulling data for job 1286, ignoring row
Update: Pulling data for job 1287
Update: Pulling data for job 1288
Update: Pulling data for job 1289
Update: Pulling data for job 1290
Update: Pulling data for job 1291
Update: Pulling data for job 1292
Update: Pulling data for job 1293
Update: Pulling data for job 1294
Update: Pulling data for job 1295
Update: Pulling data for job 1296
Update: Pulling data for job 1297
Update: Pulling data for job 1298
Update: Pulling data for job 1299
Update: Pulling data for job 1300
Update: Pulling data for job 1301
Update: Pulling data for job 1302
Update: Pulling data for job 1303
Update: Pulling data for job 1304
Update: Pulling data for job 1305
Update: Pulling data for job 1306
Update: Pulling data for job 1307
Update: Pulling data for job 1308
Update: Pulling data for job 1309
Update: Pulling data for job 1310
Update: Pulling data for job 1311
Update: Pulling data for job 1312
Update: Pulling data for job 1313
Update: Pulling data for job 1314
Update: Pulling data for job 1315
Update: Pulling data for job 1316
Update: Pulling data for job 1317
Update: Pulling data for job 1318
Update: Pulling data for job 1319
Update: Pulling data for job 1320
Update: Pulling data for job 1321
Error: Error pulling data for job 1321, executing attempt 2
Update: Pulling data for job 1322
Update: Pulling data for job 1323
Update: Pulling data for job 1324
Update: Pulling data for job 1325
Update: Pulling data for job 1326
Update: Pulling data for job 1327
Update: Pulling data for job 1328
Update: Pulling data for job 1329
Update: Pulling data for job 1330
Update: Pulling data for job 1331
Update: Pulling data for job 1332
Update: Pulling data for job 1333
Update: Pulling data for job 1334
Update: Pulling data for job 1335
Update: Pulling data for job 1336
Update: Pulling data for job 1337
Update: Pulling data for job 1338
Update: Pulling data for job 1339
Update: Pulling data for job 1340
Update: Pulling data for job 1341
Update: Pulling data for job 1342
Update: Pulling data for job 1343
Error: Error pulling data for job 1343, executing attempt 2
Update: Pulling data for job 1344
Update: Pulling data for job 1345
Error: Error pulling data for job 1345, executing attempt 2
Update: Pulling data for job 1346
Update: Pulling data for job 1347
Update: Pulling data for job 1348
Update: Pulling data for job 1349
Update: Pulling data for job 1350
Update: Pulling data for job 1351
Update: Pulling data for job 1352
Update: Pulling data for job 1353
Update: Pulling data for job 1354
Error: Error pulling data for job 1354, executing attempt 2
Update: Pulling data for job 1355
Update: Pulling data for job 1356
Update: Pulling data for job 1357
Update: Pulling data for job 1358
Update: Pulling data for job 1359
Update: Pulling data for job 1360
Update: Pulling data for job 1361
Update: Pulling data for job 1362
Update: Pulling data for job 1363
Update: Pulling data for job 1364
Error: Error pulling data for job 1364, executing attempt 2

Update: Pulling data for job 1365
Error: Error pulling data for job 1365, executing attempt 2
Update: Pulling data for job 1366
Update: Pulling data for job 1367
Update: Pulling data for job 1368
Update: Pulling data for job 1369
Update: Pulling data for job 1370
Update: Pulling data for job 1371
Update: Pulling data for job 1372
Update: Pulling data for job 1373
Update: Pulling data for job 1374
Update: Pulling data for job 1375
Update: Pulling data for job 1376
Update: Pulling data for job 1377
Update: Pulling data for job 1378
Update: Pulling data for job 1379
Update: Pulling data for job 1380
Update: Pulling data for job 1381
Update: Pulling data for job 1382
Update: Pulling data for job 1383
Update: Pulling data for job 1384
Update: Pulling data for job 1385
Update: Pulling data for job 1386
Update: Pulling data for job 1387
Update: Pulling data for job 1388
Update: Pulling data for job 1389
Update: Pulling data for job 1390
Update: Pulling data for job 1391
Update: Pulling data for job 1392
Update: Pulling data for job 1393
Update: Pulling data for job 1394
Update: Pulling data for job 1395
Update: Pulling data for job 1396
Update: Pulling data for job 1397
Update: Pulling data for job 1398
Update: Pulling data for job 1399
Update: Pulling data for job 1400
Error: Error pulling data for job 1400, executing attempt 2
Update: Pulling data for job 1401
Error: Error pulling data for job 1401, executing attempt 2
Update: Pulling data for job 1402
Update: Pulling data for job 1403
Update: Pulling data for job 1404
Update: Pulling data for job 1405
Update: Pulling data for job 1406
Update: Pulling data for job 1407
Update: Pulling data for job 1408
Update: Pulling data for job 1409
Update: Pulling data for job 1410
Update: Pulling data for job 1411
Update: Pulling data for job 1412
Update: Pulling data for job 1413
Update: Pulling data for job 1414
Update: Pulling data for job 1415
Update: Pulling data for job 1416
Update: Pulling data for job 1417
Update: Pulling data for job 1418
Update: Pulling data for job 1419
Update: Pulling data for job 1420
Update: Pulling data for job 1421
Update: Pulling data for job 1422
Update: Pulling data for job 1423
Update: Pulling data for job 1424
Update: Pulling data for job 1425
Update: Pulling data for job 1426
Update: Pulling data for job 1427
Update: Pulling data for job 1428
Update: Pulling data for job 1429
Update: Pulling data for job 1430
Update: Pulling data for job 1431
Update: Pulling data for job 1432
Update: Pulling data for job 1433
Update: Pulling data for job 1434
Update: Pulling data for job 1435
Update: Pulling data for job 1436
Update: Pulling data for job 1437
Update: Pulling data for job 1438
Update: Pulling data for job 1439
Update: Pulling data for job 1440
Update: Pulling data for job 1441
Update: Pulling data for job 1442
Update: Pulling data for job 1443
Update: Pulling data for job 1444
Update: Pulling data for job 1445
Update: Pulling data for job 1446
Update: Pulling data for job 1447
Update: Pulling data for job 1448
Update: Pulling data for job 1449
Update: Pulling data for job 1450
Update: Pulling data for job 1451
Update: Pulling data for job 1452
Update: Pulling data for job 1453
Update: Pulling data for job 1454
Update: Pulling data for job 1455
Update: Pulling data for job 1456
Update: Pulling data for job 1457
Update: Pulling data for job 1458
Update: Pulling data for job 1459
Update: Pulling data for job 1460
Update: Pulling data for job 1461
Update: Pulling data for job 1462
Update: Pulling data for job 1463
Update: Pulling data for job 1464
Update: Pulling data for job 1465
Update: Pulling data for job 1466
Update: Pulling data for job 1467
Update: Pulling data for job 1468
Update: Pulling data for job 1469
Update: Pulling data for job 1470
Update: Pulling data for job 1471
Update: Pulling data for job 1472
Update: Pulling data for job 1473
Update: Pulling data for job 1474
Update: Pulling data for job 1475
Update: Pulling data for job 1476
Update: Pulling data for job 1477
Update: Pulling data for job 1478
Error: Error pulling data for job 1478, executing attempt 2
Error: Error pulling data for job 1478, executing attempt 3
Error: Error pulling data for job 1478, ignoring row
Update: Pulling data for job 1479
Update: Pulling data for job 1480
Update: Pulling data for job 1481
Update: Pulling data for job 1482
Update: Pulling data for job 1483
Update: Pulling data for job 1484
Error: Error pulling data for job 1484, executing attempt 2
Error: Error pulling data for job 1484, executing attempt 3
Error: Error pulling data for job 1484, ignoring row
Update: Pulling data for job 1485
Error: Error pulling data for job 1485, executing attempt 2
Error: Error pulling data for job 1485, executing attempt 3
Error: Error pulling data for job 1485, ignoring row
Update: Pulling data for job 1486
Error: Error pulling data for job 1486, executing attempt 2
Error: Error pulling data for job 1486, executing attempt 3
Error: Error pulling data for job 1486, ignoring row
Update: Pulling data for job 1487
Update: Pulling data for job 1488
Update: Pulling data for job 1489
Update: Pulling data for job 1490
Update: Pulling data for job 1491
Error: Error pulling data for job 1491, executing attempt 2
Error: Error pulling data for job 1491, executing attempt 3
Error: Error pulling data for job 1491, ignoring row
Update: Pulling data for job 1492
Update: Pulling data for job 1493
Update: Pulling data for job 1494
Update: Pulling data for job 1495
Update: Pulling data for job 1496
Update: Pulling data for job 1497
Update: Pulling data for job 1498
Update: Pulling data for job 1499
Update: Pulling data for job 1500
Error: Error pulling data for job 1500, executing attempt 2
Update: Pulling data for job 1501
Update: Pulling data for job 1502
Update: Pulling data for job 1503
Update: Pulling data for job 1504
Update: Pulling data for job 1505
Update: Pulling data for job 1506
Update: Pulling data for job 1507
Update: Pulling data for job 1508
Update: Pulling data for job 1509
Update: Pulling data for job 1510
Update: Pulling data for job 1511
Update: Pulling data for job 1512
Error: Error pulling data for job 1512, executing attempt 2
Update: Pulling data for job 1513
Update: Pulling data for job 1514
Update: Pulling data for job 1515
Update: Pulling data for job 1516
Update: Pulling data for job 1517
Update: Pulling data for job 1518
Update: Pulling data for job 1519
Update: Pulling data for job 1520
Update: Pulling data for job 1521
Update: Pulling data for job 1522
Update: Pulling data for job 1523
Update: Pulling data for job 1524
Update: Pulling data for job 1525
Update: Pulling data for job 1526
Update: Pulling data for job 1527
Update: Pulling data for job 1528
Update: Pulling data for job 1529
Update: Pulling data for job 1530
Update: Pulling data for job 1531
Update: Pulling data for job 1532
Update: Pulling data for job 1533
Update: Pulling data for job 1534
Update: Pulling data for job 1535
Update: Pulling data for job 1536
Update: Pulling data for job 1537
Update: Pulling data for job 1538
Update: Pulling data for job 1539
Update: Pulling data for job 1540
Update: Pulling data for job 1541
Update: Pulling data for job 1542
Update: Pulling data for job 1543
Update: Pulling data for job 1544
Update: Pulling data for job 1545
Update: Pulling data for job 1546
Update: Pulling data for job 1547
Update: Pulling data for job 1548
Update: Pulling data for job 1549
Update: Pulling data for job 1550
Update: Pulling data for job 1551
Update: Pulling data for job 1552
Update: Pulling data for job 1553
Update: Pulling data for job 1554
Update: Pulling data for job 1555
Update: Pulling data for job 1556
Update: Pulling data for job 1557
Update: Pulling data for job 1558
Update: Pulling data for job 1559
Update: Pulling data for job 1560
Update: Pulling data for job 1561
Update: Pulling data for job 1562
Update: Pulling data for job 1563
Error: Error pulling data for job 1563, executing attempt 2
Error: Error pulling data for job 1563, executing attempt 3
Error: Error pulling data for job 1563, ignoring row
Update: Pulling data for job 1564
Error: Error pulling data for job 1564, executing attempt 2

Error: Error pulling data for job 1564, executing attempt 3
Error: Error pulling data for job 1564, ignoring row
Update: Pulling data for job 1565
Update: Pulling data for job 1566
Update: Pulling data for job 1567
Update: Pulling data for job 1568
Update: Pulling data for job 1569
Update: Pulling data for job 1570
Update: Pulling data for job 1571
Update: Pulling data for job 1572
Update: Pulling data for job 1573
Update: Pulling data for job 1574
Update: Pulling data for job 1575
Update: Pulling data for job 1576
Update: Pulling data for job 1577
Update: Pulling data for job 1578
Update: Pulling data for job 1579
Update: Pulling data for job 1580
Update: Pulling data for job 1581
Update: Pulling data for job 1582
Update: Pulling data for job 1583
Update: Pulling data for job 1584
Update: Pulling data for job 1585
Update: Pulling data for job 1586
Update: Pulling data for job 1587
Update: Pulling data for job 1588
Update: Pulling data for job 1589
Update: Pulling data for job 1590
Update: Pulling data for job 1591
Update: Pulling data for job 1592
Update: Pulling data for job 1593
Update: Pulling data for job 1594
Update: Pulling data for job 1595
Update: Pulling data for job 1596
Update: Pulling data for job 1597
Update: Pulling data for job 1598
Update: Pulling data for job 1599
Update: Pulling data for job 1600
Update: Pulling data for job 1601
Update: Pulling data for job 1602
Update: Pulling data for job 1603
Update: Pulling data for job 1604
Update: Pulling data for job 1605
Update: Pulling data for job 1606
Update: Pulling data for job 1607
Update: Pulling data for job 1608
Update: Pulling data for job 1609
Update: Pulling data for job 1610
Update: Pulling data for job 1611
Update: Pulling data for job 1612
Update: Pulling data for job 1613
Update: Pulling data for job 1614
Update: Pulling data for job 1615
Update: Pulling data for job 1616
Update: Pulling data for job 1617
Update: Pulling data for job 1618
Update: Pulling data for job 1619
Update: Pulling data for job 1620
Update: Pulling data for job 1621
Update: Pulling data for job 1622
Update: Pulling data for job 1623
Update: Pulling data for job 1624
Update: Pulling data for job 1625
Update: Pulling data for job 1626
Update: Pulling data for job 1627
Error: Error pulling data for job 1627, executing attempt 2
Update: Pulling data for job 1628
Update: Pulling data for job 1629
Update: Pulling data for job 1630
Update: Pulling data for job 1631
Update: Pulling data for job 1632
Update: Pulling data for job 1633
Update: Pulling data for job 1634
Update: Pulling data for job 1635
Update: Pulling data for job 1636
Update: Pulling data for job 1637
Update: Pulling data for job 1638
Update: Pulling data for job 1639
Update: Pulling data for job 1640
Update: Pulling data for job 1641
Update: Pulling data for job 1642
Update: Pulling data for job 1643
Update: Pulling data for job 1644
Update: Pulling data for job 1645
Update: Pulling data for job 1646
Update: Pulling data for job 1647
Update: Pulling data for job 1648
Error: Error pulling data for job 1648, executing attempt 2
Update: Pulling data for job 1649
Update: Pulling data for job 1650
Update: Pulling data for job 1651
Update: Pulling data for job 1652
Update: Pulling data for job 1653
Update: Pulling data for job 1654
Update: Pulling data for job 1655
Update: Pulling data for job 1656
Error: Error pulling data for job 1656, executing attempt 2
Update: Pulling data for job 1657
Update: Pulling data for job 1658
Update: Pulling data for job 1659
Update: Pulling data for job 1660
Update: Pulling data for job 1661
Update: Pulling data for job 1662
Update: Pulling data for job 1663
Update: Pulling data for job 1664
Update: Pulling data for job 1665
Update: Pulling data for job 1666
Error: Error pulling data for job 1666, executing attempt 2
Update: Pulling data for job 1667
Update: Pulling data for job 1668
Update: Pulling data for job 1669
Update: Pulling data for job 1670
Update: Pulling data for job 1671
Update: Pulling data for job 1672
Update: Pulling data for job 1673
Update: Pulling data for job 1674
Update: Pulling data for job 1675
Error: Error pulling data for job 1675, executing attempt 2
Update: Pulling data for job 1676
Update: Pulling data for job 1677
Update: Pulling data for job 1678
Update: Pulling data for job 1679
Update: Pulling data for job 1680
Update: Pulling data for job 1681
Update: Pulling data for job 1682
Update: Pulling data for job 1683
Update: Pulling data for job 1684
Update: Pulling data for job 1685
Update: Pulling data for job 1686
Update: Pulling data for job 1687
Update: Pulling data for job 1688
Update: Pulling data for job 1689
Update: Pulling data for job 1690
Update: Pulling data for job 1691
Update: Pulling data for job 1692
Update: Pulling data for job 1693
Update: Pulling data for job 1694
Update: Pulling data for job 1695
Update: Pulling data for job 1696
Update: Pulling data for job 1697
Update: Pulling data for job 1698
Update: Pulling data for job 1699
Update: Pulling data for job 1700
Update: Pulling data for job 1701
Update: Pulling data for job 1702
Update: Pulling data for job 1703
Update: Pulling data for job 1704
Update: Pulling data for job 1705
Update: Pulling data for job 1706
Update: Pulling data for job 1707
Update: Pulling data for job 1708
Update: Pulling data for job 1709
Update: Pulling data for job 1710
Update: Pulling data for job 1711
Update: Pulling data for job 1712
Update: Pulling data for job 1713
Update: Pulling data for job 1714
Update: Pulling data for job 1715
Update: Pulling data for job 1716
Update: Pulling data for job 1717
Update: Pulling data for job 1718
Update: Pulling data for job 1719
Update: Pulling data for job 1720
Update: Pulling data for job 1721
Update: Pulling data for job 1722
Update: Pulling data for job 1723
Update: Pulling data for job 1724
Update: Pulling data for job 1725
Update: Pulling data for job 1726
Update: Pulling data for job 1727
Update: Pulling data for job 1728
Update: Pulling data for job 1729
Update: Pulling data for job 1730
Update: Pulling data for job 1731
Update: Pulling data for job 1732
Update: Pulling data for job 1733
Update: Pulling data for job 1734
Update: Pulling data for job 1735
Update: Pulling data for job 1736
Update: Pulling data for job 1737
Update: Pulling data for job 1738
Update: Pulling data for job 1739
Update: Pulling data for job 1740
Update: Pulling data for job 1741
Update: Pulling data for job 1742
Update: Pulling data for job 1743
Update: Pulling data for job 1744
Update: Pulling data for job 1745
Update: Pulling data for job 1746
Update: Pulling data for job 1747
Update: Pulling data for job 1748
Update: Pulling data for job 1749
Error: Error pulling data for job 1749, executing attempt 2
Update: Pulling data for job 1750
Update: Pulling data for job 1751
Update: Pulling data for job 1752
Update: Pulling data for job 1753
Update: Pulling data for job 1754
Update: Pulling data for job 1755
Update: Pulling data for job 1756
Update: Pulling data for job 1757
Update: Pulling data for job 1758
Update: Pulling data for job 1759
Update: Pulling data for job 1760
Update: Pulling data for job 1761
Update: Pulling data for job 1762
Update: Pulling data for job 1763
Update: Pulling data for job 1764
Update: Pulling data for job 1765
Update: Pulling data for job 1766
Update: Pulling data for job 1767
Update: Pulling data for job 1768
Update: Pulling data for job 1769
Update: Pulling data for job 1770
Update: Pulling data for job 1771
Update: Pulling data for job 1772
Update: Pulling data for job 1773
Update: Pulling data for job 1774
Update: Pulling data for job 1775
Update: Pulling data for job 1776
Update: Pulling data for job 1777
Update: Pulling data for job 1778
Update: Pulling data for job 1779
Update: Pulling data for job 1780
Update: Pulling data for job 1781
Update: Pulling data for job 1782
Update: Pulling data for job 1783
Update: Pulling data for job 1784
Update: Pulling data for job 1785
Update: Pulling data for job 1786
Update: Pulling data for job 1787
Update: Pulling data for job 1788
Update: Pulling data for job 1789
Update: Pulling data for job 1790
Update: Pulling data for job 1791
Update: Pulling data for job 1792

Update: Pulling data for job 1793
Update: Pulling data for job 1794
Update: Pulling data for job 1795
Update: Pulling data for job 1796
Update: Pulling data for job 1797
Update: Pulling data for job 1798
Update: Pulling data for job 1799
Update: Pulling data for job 1800
Update: Pulling data for job 1801
Update: Pulling data for job 1802
Update: Pulling data for job 1803
Update: Pulling data for job 1804
Update: Pulling data for job 1805
Update: Pulling data for job 1806
Update: Pulling data for job 1807
Update: Pulling data for job 1808
Update: Pulling data for job 1809
Update: Pulling data for job 1810
Update: Pulling data for job 1811
Update: Pulling data for job 1812
Update: Pulling data for job 1813
Update: Pulling data for job 1814
Update: Pulling data for job 1815
Update: Pulling data for job 1816
Error: Error pulling data for job 1816, executing attempt 2
Error: Error pulling data for job 1816, executing attempt 3
Error: Error pulling data for job 1816, ignoring row
Update: Pulling data for job 1817
Update: Pulling data for job 1818
Update: Pulling data for job 1819
Update: Pulling data for job 1820
Error: Error pulling data for job 1820, executing attempt 2
Error: Error pulling data for job 1820, executing attempt 3
Error: Error pulling data for job 1820, ignoring row
Update: Pulling data for job 1821
Error: Error pulling data for job 1821, executing attempt 2
Error: Error pulling data for job 1821, executing attempt 3
Error: Error pulling data for job 1821, ignoring row
Update: Pulling data for job 1822
Update: Pulling data for job 1823
Update: Pulling data for job 1824
Update: Pulling data for job 1825
Update: Pulling data for job 1826
Update: Pulling data for job 1827
Update: Pulling data for job 1828
Update: Pulling data for job 1829
Update: Pulling data for job 1830
Update: Pulling data for job 1831
Update: Pulling data for job 1832
Update: Pulling data for job 1833
Error: Error pulling data for job 1833, executing attempt 2
Update: Pulling data for job 1834
Update: Pulling data for job 1835
Update: Pulling data for job 1836
Update: Pulling data for job 1837
Update: Pulling data for job 1838
Update: Pulling data for job 1839
Update: Pulling data for job 1840
Update: Pulling data for job 1841
Update: Pulling data for job 1842
Update: Pulling data for job 1843
Update: Pulling data for job 1844
Error: Error pulling data for job 1844, executing attempt 2
Update: Pulling data for job 1845
Update: Pulling data for job 1846
Update: Pulling data for job 1847
Update: Pulling data for job 1848
Update: Pulling data for job 1849
Update: Pulling data for job 1850
Update: Pulling data for job 1851
Update: Pulling data for job 1852
Update: Pulling data for job 1853
Update: Pulling data for job 1854
Update: Pulling data for job 1855
Update: Pulling data for job 1856
Update: Pulling data for job 1857
Update: Pulling data for job 1858
Update: Pulling data for job 1859
Error: Error pulling data for job 1859, executing attempt 2
Update: Pulling data for job 1860
Update: Pulling data for job 1861
Update: Pulling data for job 1862
Update: Pulling data for job 1863
Update: Pulling data for job 1864
Error: Error pulling data for job 1864, executing attempt 2
Update: Pulling data for job 1865
Update: Pulling data for job 1866
Update: Pulling data for job 1867
Update: Pulling data for job 1868
Update: Pulling data for job 1869
Update: Pulling data for job 1870
Update: Pulling data for job 1871
Error: Error pulling data for job 1871, executing attempt 2
Update: Pulling data for job 1872
Update: Pulling data for job 1873
Update: Pulling data for job 1874
Update: Pulling data for job 1875
Update: Pulling data for job 1876
Update: Pulling data for job 1877
Update: Pulling data for job 1878
Error: Error pulling data for job 1878, executing attempt 2
Update: Pulling data for job 1879
Update: Pulling data for job 1880
Update: Pulling data for job 1881
Update: Pulling data for job 1882
Update: Pulling data for job 1883
Update: Pulling data for job 1884
Update: Pulling data for job 1885
Update: Pulling data for job 1886
Update: Pulling data for job 1887
Update: Pulling data for job 1888
Update: Pulling data for job 1889
Update: Pulling data for job 1890
Update: Pulling data for job 1891
Update: Pulling data for job 1892
Update: Pulling data for job 1893
Update: Pulling data for job 1894
Update: Pulling data for job 1895
Update: Pulling data for job 1896
Update: Pulling data for job 1897
Update: Pulling data for job 1898
Update: Pulling data for job 1899
Update: Pulling data for job 1900
Update: Pulling data for job 1901
Update: Pulling data for job 1902
Update: Pulling data for job 1903
Update: Pulling data for job 1904
Update: Pulling data for job 1905
Update: Pulling data for job 1906
Update: Pulling data for job 1907
Update: Pulling data for job 1908
Error: Error pulling data for job 1908, executing attempt 2
Error: Error pulling data for job 1908, executing attempt 3
Error: Error pulling data for job 1908, ignoring row
Update: Pulling data for job 1909
Update: Pulling data for job 1910
Update: Pulling data for job 1911
Update: Pulling data for job 1912
Update: Pulling data for job 1913
Update: Pulling data for job 1914
Update: Pulling data for job 1915
Update: Pulling data for job 1916
Update: Pulling data for job 1917
Update: Pulling data for job 1918
Update: Pulling data for job 1919
Update: Pulling data for job 1920
Update: Pulling data for job 1921
Update: Pulling data for job 1922
Update: Pulling data for job 1923
Update: Pulling data for job 1924
Update: Pulling data for job 1925

In [14]:
##############################################################
# identify which job_pull failed
##############################################################

print('Failed to retrieve {} items from site.\nIndex: {}'.format(
     len(job_pull_error_list), job_pull_error_list))

Failed to retrieve 60 items from site.
Index: [19, 34, 98, 101, 119, 134, 194, 197, 201, 205, 207, 256, 259, 270, 357, 364, 382, 384, 406, 426, 438, 451, 593, 626, 667, 671, 672, 675, 680, 686, 687, 688, 690, 691, 692, 693, 808, 829, 935, 940, 941, 1006, 1017, 1041, 1045, 1209, 1244, 1247, 1286, 1478, 1484, 1485, 1486, 1491, 1563, 1564, 1816, 1820, 1821, 1908]

In [15]:
job_details

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,JOB-2019-0036660,Data Analyst (Data Science),BLACKBOX RESEARCH PTE LTD,"SINGAPORE POST CENTRE, 10 EUNOS ROAD 8 408600",Others,https://www.mycareersfuture.sg/job/data-analys...,"[As a Data Analyst, you will take charge of th...",[],Full Time,Executive,"[Analysis, Business Analysis, Clinical Data Ma...","$2,800","$3,600",Monthly,04 May 2019,03 Jun 2019
0,JOB-2019-0094697,Data Analyst (HR) (JD#5114),SCIENTE INTERNATIONAL PTE. LTD.,"THE SIGNATURE, 51 CHANGI BUSINESS PARK CENTRAL...",Information Technology,https://www.mycareersfuture.sg/job/data-analys...,[An exciting opportunity for Analytics profess...,"[Bachelor's degree, preferably in a field of A...",Permanent,Middle Management,"[Access, Analysis, Analytics, Business Analysi...","$7,000","$12,000",Monthly,04 May 2019,03 Jun 2019
0,JOB-2019-0094154,Risk and Financial Data Analyst,CARGILL TSF ASIA PTE. LTD.,"CAPITAGREEN, 138 MARKET STREET 048946",Banking and Finance,https://www.mycareersfuture.sg/job/risk-financ...,[Cargill Trade & Capital Markets (TCM) was est...,"[A technical background, preferably in Economi...",Full Time,Professional,"[Analysis, Banking, Credit Risk, Data Analysis...","$5,500","$8,250",Monthly,03 May 2019,02 Jun 2019
0,JOB-2019-0094456,Senior Data Analyst,JONES LANG LASALLE PROPERTY CONSULTANTS PTE LTD,"REPUBLIC PLAZA, 9 RAFFLES PLACE 048619",Real Estate / Property Management,https://www.mycareersfuture.sg/job/senior-data...,[JLL is looking for a Data Quality Analyst to ...,"[Good technical writing, documentation, and co...",Full Time,Senior Executive,"[Access, Analysis, Analytics, Business Analysi...","$5,000","$7,000",Monthly,03 May 2019,02 Jun 2019
0,JOB-2019-0094395,Data Analyst,CAPGEMINI SINGAPORE PTE. LTD.,6 BATTERY ROAD 049909,Banking and Finance,https://www.mycareersfuture.sg/job/data-analys...,[Analyst profile with understanding of both. T...,[],"Permanent, Full Time",Executive,"[Access, Business Analysis, Business Intellige...","$4,500","$6,500",Monthly,03 May 2019,02 Jun 2019
0,JOB-2019-0094277,Trade Data Analyst,COMMODITIES INTELLIGENCE CENTRE PTE. LTD.,"WHEELOCK PLACE, 501 ORCHARD ROAD 238880",Others,https://www.mycareersfuture.sg/job/trade-data-...,"[As part of CIC's rapid growing, we are lookin...",[],Full Time,Executive,"[Access, Analysis, Analytics, Biostatistics, B...","$4,000","$6,000",Monthly,03 May 2019,02 Jun 2019
0,JOB-2019-0092697,Data Analyst,BIO-RAD LABORATORIES (SINGAPORE) PTE LTD,NaN,Manufacturing,https://www.mycareersfuture.sg/job/data-analys...,[],"[Bachelor Degree in Economics, Statistics or M...",Permanent,Junior Executive,"[Access, Business Analysis, Business Intellige...","$3,500","$4,800",Monthly,03 May 2019,01 Jun 2019
0,JOB-2019-0093993,Data Management Specialist,STHREE PTE. LTD.,"CHINA SQUARE CENTRAL, 18 CROSS STREET 048423",Banking and Finance,https://www.mycareersfuture.sg/job/data-manage...,[The main responsibility of the position is to...,[Hands on and relevant experience in the above...,Contract,Professional,"[Access, Analysis, Analytics, Business Analysi...","$10,000","$12,000",Monthly,03 May 2019,02 Jun 2019
0,JOB-2019-0093684,Data Planner,CHEIL SINGAPORE PTE. LTD.,NaN,Advertising / Media,https://www.mycareersfuture.sg/job/data-planne...,"[2. , 3. ]",[ from campaign planning / execution / perform...,"Permanent, Full Time",Professional,"[Access, Business Analysis, Business Intellige...",NaN,NaN,NaN,03 May 2019,02 Jun 2019
0,JOB-2019-0093269,Data Analyst,OPTIMUM SOLUTIONS (SINGAPORE) PTE LTD,"PLAZA 8 @ CBP, 1 CHANGI BUSINESS PARK CRESCENT...",Information Technology,https://www.mycareersfuture.sg/job/data-analys...,[],"[BS in Mathematics, Economics, Computer Scienc...",Full Time,Executive,"[Active Directory, Cisco Technologies, Data Ce...","$4,000","$6,000",Monthly,02 May 2019,01 Jun 2019
0,JOB-2019-0092977,Senior Data Engineer / Data Engineer,NTUC ENTERPRISE NEXUS CO-OPERATIVE LIMITED,1 MARINA BOULEVARD 018989,Information Technology,https://www.mycareersfuture.sg/job/senior-data...,[],"[Advanced degree in computer science, computer...",Full Time,Executive,"[Access, Analysis, Analytics, Business Analysi...","$4,000","$8,000",Monthly,02 May 2019,01 Jun 2019
0,JOB-2019-0093087,Product Analyst,PROPERTYGURU PTE. LTD.,"TRIPLEONE SOMERSET, 111 SOMERSET ROAD 238164","Engineering, Information Technology",https://www.mycareersfuture.sg/job/product-ana...,[PropertyGuru Group is Asia’s leading online p...,[Bachelor’s degree in IT or relevant field. Al...,"Permanent, Full Time","Professional, Senior Executive","[Access, Analysis, Analytics, Business Analysi...","$7,000","$9,000",Monthly,02 May 2019,01 Jun 2019
0,JOB-2019-0091656,Data Analyst,SHIPSFOCUS INTELLIGENCE PTE. LTD.,"CONNEXIS, 1 FUSIONOPOLIS WAY 138632","Engineering, Information Technology, Others",https://www.mycareersfuture.sg/job/data-analys...,[Passionate in chemical shipping research? Cra...,[Experience in the Data Science & Engineering ...,"Permanent, Full Time","Fresh/entry level, Junior Executive","[Analysis, Business Analysis, Business Strateg...",NaN,NaN,NaN,30 Apr 2019,30 May 2019
0,JOB-2019-0091702,"Analyst, Operations Intelligence Data Science ...",DBS BANK LTD.,"MARINA BAY FINANCIAL CENTRE, 12 MARINA BOULEVA...",Banking and Finance,https://www.mycareersfuture.sg/job/analyst-ope...,[Group Technology and Operations (T&O) enables...,"[2 years experiences, Well versed with data po...","Permanent, Full Time",Executive,"[Analysis, Business Analysis, Business Strateg...","$2,550","$4,600",Monthly,30 Apr 2019,30 May 2019
0,JOB-2019-0019774,IT Executive (Data Analyst),SKY PREMIUM INTERNATIONAL PTE. LTD.,"ONE RAFFLES PLACE, 1 RAFFLES PLACE 048616",Information Technology,https://www.mycareersfuture.sg/job/executive-s...,[Sky Premium International is looking for IT E...,[],Full Time,Executive,"[Active Directory, Business Analysis, CRM, ERP...","$2,500","$4,000",Monthly,29 Apr 2019,29 May 2019
0,JOB-2019-0091291,Data Analyst,CAPGEMINI SINGAPORE PTE. LTD.,6 BATTERY ROAD 049909,Engineering,https://www.mycareersfuture.sg/job/data-analys...,[•Frontline team members who have to mix solid...,[],Permanent,Professional,"[Active Directory, Cisco Technologies, Data Ce...","$5,000","$7,500",Monthly,29 Apr 2019,29 May 2019
0,JOB-2019-0090798,Data Analyst [Powerbi] - 6 months,BUSINESS EDGE PERSONNEL SERVICES PTE LTD,"SINGAPORE SHOPPING CENTRE, 190 CLEMENCEAU AVEN...",Admin / Secretarial,https://www.mycareersfuture.sg/job/data-analys...,"[Location: Outram, Salary: up to $14.50 per ho...",[Diploma/Bachelor’s Degree in Statistics or An...,Contract,Executive,"[Analysis, Business Analysis, Clinical Data Ma...","$1,800","$2,300",Monthly,29 Apr 2019,29 May 2019
0,JOB-2019-0090963,"Senior Analyst, Data Architect",SCOOT TIGERAIR PTE. LTD.,"AIRLINE HOUSE, 25 AIRLINE ROAD 819829",Information Technology,https://www.mycareersfuture.sg/job/senior-anal...,[ ],[A Bachelor’s degree from an accredited colleg...,Full Time,Senior Executive,"[Active Directory, Business Analysis, Database...",NaN,NaN,NaN,29 Apr 2019,29 May 2019
0,JOB-2019-0091477,"VP / AVP, Wealth Mgmt Technical Business Analy...",DBS BANK LTD.,NaN,Banking and Finance,https://www.mycareersfuture.sg/job/vp-avp-weal...,[The new hire will support a portfolio of appl...,[At least 8-10 years’ experience in Wealth Man...,"Permanent, Full Time","Middle Management, Manager, Professional","[Business Development, Business Strategy, Cros...","$7,000","$14,000",Monthly,29 Apr 2019,29 May 2019
0,JOB-2019-0004573,Senior Data Analyst,STREETSINE SINGAPORE PTE. LTD.,"NEWS CENTRE, 1000 TOA PAYOH NORTH 318994",Information Technology,https://www.mycareersfuture.sg/job/senior-data...,[We are currently looking for a Senior Data An...,[Minimum 2 years of relevant work experience w...,"Permanent, Full Time","Professional, Executive","[Agile Methodologies, Business Analysis, Busin...","$4,000","$8,000",Monthly,26 Apr 2019,26 May 2019
0,JOB-2019-0089696,Mid Level Data Analyst,TRAVELOKA SERVICES PTE. LTD.,NaN,Information Technology,https://www.mycareersfuture.sg/job/mid-level-d...,[Data Analyst at Traveloka is at the forefront...,"[ \t, \t, \t, \t, \t, \t, \t, \t, \t, ...",Permanent,Junior Executive,"[.NET, Agile Methodologies, ASP.NET, Business ...","$4,300","$7,600",Monthly,26 Apr 2019,26 May 2019
0,JOB-2019-0089321,Platform Engineer,GUMI ASIA PTE. LTD.,"CONNEXIS, 1 FUSIONOPOLIS WAY 138632",Information Technology,https://www.mycareersfuture.sg/job/platform-en...,[Responsible for programming and maintaining m...,[Coding/Scripting experience in languages such...,Full Time,Executive,"[ActionScript, C#, C++, Computer Games, Direct...","$5,000","$6,500",Monthly,26 Apr 2019,26 May 2019
0,JOB-2019-0089689,Data Analytics Lead,TRAVELOKA SERVICES PTE. LTD.,NaN,Information Technology,https://www.mycareersfuture.sg/job/data-analyt...,"[You will be responsible for defining, collect...","[Passion in data analysis, mathematics, statis...",Permanent,Manager,"[Analysis, Analytics, Business Analytics, Busi...","$8,300","$15,000",Monthly,26 Apr 2019,26 May 2019
0,JOB-2019-0088666,Senior Data Analyst,PROPERTYGURU PTE. LTD.,"TRIPLEONE SOMERSET, 111 SOMERSET ROAD 238164","Engineering, Information Technology",https://www.mycareersfuture.sg/job/senior-data...,[PropertyGuru Group is Asia’s leading online p...,[Bachelor’s degree in IT or relevant field. Al...,"Permanent, Full Time","Professional, Senior Executive","[Access, Analysis, Analytics, Business Analysi...","$6,000","$8,000",Monthly,25 Apr 2019,25 May 2019
0,JOB-2019-0058738,Data Analyst,INNOSPIRE PTE. LTD.,NaN,Information Technology,https://www.mycareersfuture.sg/job/data-analys...,"[ , ]","[Degree in Mathematics, Economics, Computer Sc...",Permanent,Senior Executive,"[.NET, Agile Methodologies, CSS, Data Warehous...",NaN,NaN,NaN,25 Apr 2019,25 May 2019
0,JOB-2019-0088646,Data Engineer,Company Undisclosed,"MAPLETREE BUSINESS CITY, 30 PASIR PANJANG ROAD...",Advertising / Media,https://www.mycareersfuture.sg/job/data-engine...,[As Senior Data Engineer you will have a prove...,[6 years hands-on experience in the data platf...,Permanent,Professional,"[Access, Business Analysis, Business Intellige...","$8,000","$10,000",Monthly,25 Apr 2019,25 May 2019
0,JOB-2019-0087097,CRM Data Analyst,ASPIRE GLOBAL NETWORK PTE. LTD.,"CHINA SQUARE CENTRAL, 18 CROSS STREET 048423",Information Technology,https://www.mycareersfuture.sg/job/crm-data-an...,"[ , A well-established British recruitment com...","[At least 2 years of data analysis, coding and...",Permanent,Professional,"[Access, Business Analysis, Business Intellige...","$3,500","$6,200",Monthly,24 Apr 2019,24 May 2019
0,JOB-2019-0087076,CRM Data Analyst,ASPIRE GLOBAL NETWORK PTE. LTD.,"CHINA SQUARE CENTRAL, 18 CROSS STREET 048423",Information Technology,https://www.mycareersfuture.sg/job/crm-data-an...,[A well-established British recruitment compan...,"[At least 5 years of data analysis, coding and...",Permanent,"Professional, Executive","[.NET, Agile Methodologies, ASP.NET, Business ...","$6,000","$10,000",Monthly,24 Apr 2019,24 May 2019
0,JOB-2019-0045362,Data Analyst,ZEEMART PTE. LTD.,"TOWNERVILLE, 93 MCNAIR ROAD 328560",Information Technology,https://www.mycareersfuture.sg/job/data-analys...,[You will be part of a very vibrant and dynami...,[Analytical mind with sound business insights....,Full Time,Professional,"[Analysis, Business Analysis, Business Strateg...","$4,000","$6,000",Monthly,24 Apr 2019,24 May 2019
0,JOB-2019-0087316,Technical Data Analyst,ECLERX PRIVATE LIMITED,"HIGH STREET CENTRE, 1 NORTH BRIDGE ROAD 179094",Consulting,https://www.mycareersfuture.sg/job/technical-d...,[The successful candidate will be responsible ...,[],Contract,Professional,"[Analysis, Business Analysis, Business Intelli...","$8,000","$10,000",Monthly,24 Apr 2019,24 May 2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,JOB-2019-0081803,Software Engineer - Competitive Pricing,FOODPANDA SINGAPORE PTE. LTD.,"GB BUILDING, 143 CECIL STREET 069542","Engineering, Information Technology",https://www.mycareersfuture.sg/job/software-en...,[“There is no love sincerer than the love of f...,"[ \t, \t, \t, \t, \t, \t, \t, \t, \t, ...",Full Time,"Executive, Junior Executive","[Business Analysis, Business Process Improveme...","$3,500","$7,000",Monthly,16 Apr 2019,16 May 2019
0,JOB-2019-0080157,Project Manager- Business Intelligence,EIRE SYSTEMS SINGAPORE PTE. LTD.,"KEPPEL BAY TOWER, 1 HARBOURFRONT AVENUE 098632",Information Technology,https://www.mycareersfuture.sg/job/project-man...,[We are looking to hire a Project manager with...,"[Proven, complex project management capability...",Full Time,Manager,"[Budgets, Business Analysis, Business Developm...","$7,000","$10,000",Monthly,15 Apr 2019,15 May 2019
0,JOB-2019-0079550,Analytics Engineer,ST ENGINEERING MANAGEMENT SERVICES PTE. LTD.,"ST ENGINEERING HUB, 1 ANG MO KIO ELECTRONICS P...",Information Technology,https://www.mycareersfuture.sg/job/analytics-e...,[The Analytics System team is seeking an excep...,"[Knows Tableau, D3,.NET Programming, C, Java S...",Permanent,Executive,"[Agile Methodologies, C, C#, C++, CSS, Eclipse...","$5,000","$8,000",Monthly,15 Apr 2019,15 May 2019
0,JOB-2019-0079262,Associate Incentives Accounting,SABRE ASIA PACIFIC PTE. LTD.,"ABACUS PLAZA, 3 TAMPINES CENTRAL 1 529540",Accounting / Auditing / Taxation,https://www.mycareersfuture.sg/job/associate-i...,[Sabre is a technology solutions provider to t...,[],Full Time,Executive,"[Account Reconciliation, Accounting, Accounts ...","$34,700","$64,500",Annually,15 Apr 2019,15 May 2019
0,JOB-2019-0041546,Marketing and Admin Executive,FITNESS FACTORY PTE. LTD.,82 BOAT QUAY 049870,"Admin / Secretarial, Customer Service, Marketi...",https://www.mycareersfuture.sg/job/marketing-a...,[Provide support in Marketing and Administrati...,[Diploma in Mass Communication/Marketing or eq...,Full Time,Fresh/entry level,"[Advertising, Customer Service, Digital Market...","$1,800","$2,200",Monthly,15 Apr 2019,15 May 2019
0,JOB-2019-0079940,Associate General Manager- Digital and Analytics,HCL SINGAPORE PTE. LTD.,"AXA TOWER, 8 SHENTON WAY 068811",Information Technology,https://www.mycareersfuture.sg/job/associate-g...,[Vacancy is to lead the data stream for HCL's ...,[],Permanent,Middle Management,"[Budgets, Customer Satisfaction, Customer Serv...","$11,000","$12,000",Monthly,15 Apr 2019,15 May 2019
0,JOB-2019-0079850,Business intelligence PMO Manager,Company Undisclosed,NaN,Information Technology,https://www.mycareersfuture.sg/job/business-in...,[INPUT: Key projects and initiatives aligned t...,[],Permanent,Professional,"[Budgets, Business Analysis, Business Developm...","$8,000","$11,000",Monthly,15 Apr 2019,15 May 2019
0,JOB-2019-0079192,"Technology Risk Associate (FAIT), Advisory, Si...",ERNST & YOUNG ADVISORY PTE. LTD.,1 RAFFLES QUAY 048583,Accounting / Auditing / Taxation,https://www.mycareersfuture.sg/job/technology-...,[Our Technology Risk services are designed for...,"[A recognized university degree in accounting,...",Permanent,Executive,"[Auditing, Business Continuity, Business Proce...","$3,000","$6,000",Monthly,14 Apr 2019,14 May 2019
0,JOB-2019-0079191,Technology Risk Senior Associate (Financial Au...,ERNST & YOUNG ADVISORY PTE. LTD.,1 RAFFLES QUAY 048583,Accounting / Auditing / Taxation,https://www.mycareersfuture.sg/job/technology-...,[Our Technology Risk services are designed for...,"[A recognized university degree in accounting,...",Permanent,Executive,"[Auditing, Business Continuity, Business Proce...","$4,100","$8,200",Monthly,14 Apr 2019,14 May 2019
0,JOB-2019-0079193,"Technology Risk Manager (Financial Audit IT), ...",ERNST & YOUNG ADVISORY PTE. LTD.,1 RAFFLES QUAY 048583,Accounting / Auditing / Taxation,https://www.mycareersfuture.sg/job/technology-...,[Our Technology Risk services are designed for...,"[ , , , , , , , , , , , , , , , ...",Permanent,Manager,"[Auditing, Business Process, Change Management...","$6,000","$12,000",Monthly,14 Apr 2019,14 May 2019
0,JOB-2019-0077868,Research Fellow,NATIONAL UNIVERSITY OF SINGAPORE,21 LOWER KENT RIDGE ROAD 119077,Sciences / Laboratory / R&D,https://www.mycareersfuture.sg/job/research-fe...,"[ , , The National University of Singapore in...","[A PhD degree in a relevant area;, Good public...",Full Time,Professional,"[Algorithms, Artificial Intelligence, Biochemi...","$6,000","$7,200",Monthly,12 Apr 2019,12 May 2019
0,JOB-2019-0077557,AX Technical Consultant,GOODRICH GLOBAL PTE. LTD.,"GOODRICH BUILDING, 8 CHANGI SOUTH LANE 486113",Information Technology,https://www.mycareersfuture.sg/job/ax-technica...,[1. Maintain and support daily operations or i...,[],Permanent,Professional,"[Agile Methodologies, Business Analysis, Busin...",NaN,NaN,NaN,11 Apr 2019,11 May 2019
0,JOB-2019-0076443,Deployment Project Manager,TECH MAHINDRA LIMITED (SINGAPORE BRANCH),"HONEYWELL BUILDING, 17 CHANGI BUSINESS PARK CE...",Information Technology,https://www.mycareersfuture.sg/job/deployment-...,[Minimum five (5) years of IT experience with ...,[],Permanent,Executive,"[Budgets, Business Analysis, Business Developm...","$6,500","$7,500",Monthly,10 Apr 2019,10 May 2019
0,JOB-2019-0074900,Procurement Business Intelligence (19001366),GLOBALFOUNDRIES SINGAPORE PTE. LTD.,60 WOODLANDS IND PARK D STREET 2 738406,"Information Technology, Purchasing / Merchandi...",https://www.mycareersfuture.sg/job/procurement...,[GLOBALFOUNDRIES Global Supply Management (GSM...,"[B.S. Degree in Business, Information Systems ...","Permanent, Full Time",Executive,"[Analysis, Budgets, Contract Management, Contr...","$5,400","$8,000",Monthly,09 Apr 2019,09 May 2019
0,JOB-2019-0074749,"Associate Director, Business Intelligence and ...",KROLL ASSOCIATES (S) PTE LTD,"CITY HOUSE, 36 ROBINSON ROAD 068877",Professional Services,https://www.mycareersfuture.sg/job/associate-d...,[Kroll’s Business Intelligence and Investigati...,"[Provide expert, reliable and robust analysis ...",Full Time,Middle Management,"[Biotechnology, Business Development, Business...","$5,000","$6,800",Monthly,09 Apr 2019,09 May 2019
0,JOB-2019-0074416,Business Intelligence Analyst,AMAZON WEB SERVICES SINGAPORE PRIVATE LIMITED,"AIA TOWER, 1 ROBINSON ROAD 048542",Information Technology,https://www.mycareersfuture.sg/job/business-in...,"[ ("", "") enables customers of all sizes to run...","[Bachelor’s degree in Business Administration,...",Permanent,Executive,"[Analysis, Business Analysis, Business Intelli...","$8,000","$11,000",Monthly,09 Apr 2019,09 May 2019
0,JOB-2019-0075186,"Junior Analyst, Marketing Business Intelligence",GRABTAXI HOLDINGS PTE. LTD.,"OUE DOWNTOWN, 6 SHENTON WAY 068809",Others,https://www.mycareersfuture.sg/job/junior-anal...,"[:, To design, set up, and maintain series of ...","[Bachelor’s degree in Statistics, Analytics, E...",Full Time,Executive,"[Analysis, Business Analysis, Business Strateg...","$4,500","$6,500",Monthly,09 Apr 2019,09 May 2019
0,JOB-2019-0074687,"Business and Operations Manager, Google Cloud ...",GOOGLE ASIA PACIFIC PTE. LTD.,"MARINA BAY FINANCIAL CENTRE, 8 MARINA BOULEVAR...",General Management,https://www.mycareersfuture.sg/job/business-op...,"[Google is not a conventional company, and we ...",[],Full Time,Executive,"[Business Development, Business Strategy, CRM,...","$7,500","$15,000",Monthly,09 Apr 2019,09 May 2019
0,JOB-2019-0075480,SENIOR DATA ANALYST,ASPIRE NXT PTE. LTD.,NaN,"Consulting , Information Technology",https://www.mycareersfuture.sg/job/senior-data...,"[Primary Responsibilities:, A member of our D...","[3+ years relevant industry experience, M.Sc./...",Permanent,Senior Executive,"[Analysis, Business Analysis, Clinical Data Ma...","$4,000","$7,500",Monthly,09 Apr 2019,09 May 2019
0,JOB-2019-0049206,Assistant Manager,MARINA BAY SANDS PTE. LTD.,80 ROBINSON ROAD 068898,Travel / Tourism,https://www.mycareersfuture.sg/job/assistant-m...,[],[Bachelors or Master’s degree with depth of kn...,Permanent,Manager,"[Business Development, Business Strategy, Cust...","$4,500","$7,000",Monthly,09 Apr 2019,09 May 2019

In [16]:
##############################################################
# pull the failed jobs again
##############################################################

# for row_count in [5]: # to run 1 item only
for row_count in job_pull_error_list:

    print('Update: Pulling data for job {}'.format(row_count))
    try:
        job_details = job_details.append([pull_job_details(job_links[row_count], 'mcf')])
    except:
        print('Error: Error pulling data for job {}, executing attempt 2'.format(row_count))
        try:
            job_details = job_details.append([pull_job_details(job_links[row_count], 'mcf')])
        except:
            print('Error: Error pulling data for job {}, executing attempt 3'.format(row_count))
            try:
                job_details = job_details.append([pull_job_details(job_links[row_count], 'mcf')])
            except:
                print('Error: Error pulling data for job {}, ignoring row'.format(row_count))
                job_pull_error_list_2.append(row_count)

Update: Pulling data for job 19
Error: Error pulling data for job 19, executing attempt 2
Error: Error pulling data for job 19, executing attempt 3
Error: Error pulling data for job 19, ignoring row
Update: Pulling data for job 34
Error: Error pulling data for job 34, executing attempt 2
Error: Error pulling data for job 34, executing attempt 3
Error: Error pulling data for job 34, ignoring row
Update: Pulling data for job 98
Error: Error pulling data for job 98, executing attempt 2
Error: Error pulling data for job 98, executing attempt 3
Error: Error pulling data for job 98, ignoring row
Update: Pulling data for job 101
Error: Error pulling data for job 101, executing attempt 2
Error: Error pulling data for job 101, executing attempt 3
Error: Error pulling data for job 101, ignoring row
Update: Pulling data for job 119
Error: Error pulling data for job 119, executing attempt 2
Error: Error pulling data for job 119, executing attempt 3
Error: Error pulling data for job 119, ignoring row
Update: Pulling data for job 134
Error: Error pulling data for job 134, executing attempt 2
Error: Error pulling data for job 134, executing attempt 3
Error: Error pulling data for job 134, ignoring row
Update: Pulling data for job 194
Error: Error pulling data for job 194, executing attempt 2
Error: Error pulling data for job 194, executing attempt 3
Error: Error pulling data for job 194, ignoring row
Update: Pulling data for job 197
Error: Error pulling data for job 197, executing attempt 2
Error: Error pulling data for job 197, executing attempt 3
Error: Error pulling data for job 197, ignoring row
Update: Pulling data for job 201
Error: Error pulling data for job 201, executing attempt 2
Error: Error pulling data for job 201, executing attempt 3
Error: Error pulling data for job 201, ignoring row
Update: Pulling data for job 205
Error: Error pulling data for job 205, executing attempt 2
Error: Error pulling data for job 205, executing attempt 3
Error: Error pulling data for job 205, ignoring row
Update: Pulling data for job 207
Error: Error pulling data for job 207, executing attempt 2
Error: Error pulling data for job 207, executing attempt 3
Error: Error pulling data for job 207, ignoring row
Update: Pulling data for job 256
Error: Error pulling data for job 256, executing attempt 2
Error: Error pulling data for job 256, executing attempt 3
Error: Error pulling data for job 256, ignoring row
Update: Pulling data for job 259
Error: Error pulling data for job 259, executing attempt 2
Error: Error pulling data for job 259, executing attempt 3
Error: Error pulling data for job 259, ignoring row
Update: Pulling data for job 270
Error: Error pulling data for job 270, executing attempt 2
Error: Error pulling data for job 270, executing attempt 3
Error: Error pulling data for job 270, ignoring row
Update: Pulling data for job 357
Error: Error pulling data for job 357, executing attempt 2
Error: Error pulling data for job 357, executing attempt 3
Error: Error pulling data for job 357, ignoring row
Update: Pulling data for job 364
Error: Error pulling data for job 364, executing attempt 2
Error: Error pulling data for job 364, executing attempt 3
Error: Error pulling data for job 364, ignoring row
Update: Pulling data for job 382
Error: Error pulling data for job 382, executing attempt 2
Error: Error pulling data for job 382, executing attempt 3
Error: Error pulling data for job 382, ignoring row
Update: Pulling data for job 384
Error: Error pulling data for job 384, executing attempt 2
Error: Error pulling data for job 384, executing attempt 3
Error: Error pulling data for job 384, ignoring row
Update: Pulling data for job 406
Error: Error pulling data for job 406, executing attempt 2
Error: Error pulling data for job 406, executing attempt 3
Error: Error pulling data for job 406, ignoring row
Update: Pulling data for job 426
Error: Error pulling data for job 426, executing attempt 2
Error: Error pulling data for job 426, executing attempt 3
Error: Error pulling data for job 426, ignoring row
Update: Pulling data for job 438
Error: Error pulling data for job 438, executing attempt 2
Error: Error pulling data for job 438, executing attempt 3
Error: Error pulling data for job 438, ignoring row
Update: Pulling data for job 451
Error: Error pulling data for job 451, executing attempt 2
Error: Error pulling data for job 451, executing attempt 3
Error: Error pulling data for job 451, ignoring row
Update: Pulling data for job 593
Error: Error pulling data for job 593, executing attempt 2
Error: Error pulling data for job 593, executing attempt 3
Error: Error pulling data for job 593, ignoring row
Update: Pulling data for job 626
Error: Error pulling data for job 626, executing attempt 2
Error: Error pulling data for job 626, executing attempt 3
Error: Error pulling data for job 626, ignoring row
Update: Pulling data for job 667
Error: Error pulling data for job 667, executing attempt 2
Error: Error pulling data for job 667, executing attempt 3
Error: Error pulling data for job 667, ignoring row
Update: Pulling data for job 671
Error: Error pulling data for job 671, executing attempt 2
Error: Error pulling data for job 671, executing attempt 3
Error: Error pulling data for job 671, ignoring row
Update: Pulling data for job 672
Error: Error pulling data for job 672, executing attempt 2
Error: Error pulling data for job 672, executing attempt 3
Error: Error pulling data for job 672, ignoring row
Update: Pulling data for job 675
Error: Error pulling data for job 675, executing attempt 2
Error: Error pulling data for job 675, executing attempt 3
Error: Error pulling data for job 675, ignoring row
Update: Pulling data for job 680
Error: Error pulling data for job 680, executing attempt 2
Error: Error pulling data for job 680, executing attempt 3
Error: Error pulling data for job 680, ignoring row
Update: Pulling data for job 686
Error: Error pulling data for job 686, executing attempt 2
Error: Error pulling data for job 686, executing attempt 3
Error: Error pulling data for job 686, ignoring row
Update: Pulling data for job 687
Error: Error pulling data for job 687, executing attempt 2
Error: Error pulling data for job 687, executing attempt 3
Error: Error pulling data for job 687, ignoring row
Update: Pulling data for job 688
Error: Error pulling data for job 688, executing attempt 2
Error: Error pulling data for job 688, executing attempt 3
Error: Error pulling data for job 688, ignoring row
Update: Pulling data for job 690
Error: Error pulling data for job 690, executing attempt 2
Error: Error pulling data for job 690, executing attempt 3
Error: Error pulling data for job 690, ignoring row
Update: Pulling data for job 691
Error: Error pulling data for job 691, executing attempt 2
Error: Error pulling data for job 691, executing attempt 3
Error: Error pulling data for job 691, ignoring row
Update: Pulling data for job 692
Error: Error pulling data for job 692, executing attempt 2
Error: Error pulling data for job 692, executing attempt 3
Error: Error pulling data for job 692, ignoring row
Update: Pulling data for job 693
Error: Error pulling data for job 693, executing attempt 2
Error: Error pulling data for job 693, executing attempt 3
Error: Error pulling data for job 693, ignoring row
Update: Pulling data for job 808
Error: Error pulling data for job 808, executing attempt 2
Error: Error pulling data for job 808, executing attempt 3
Error: Error pulling data for job 808, ignoring row
Update: Pulling data for job 829
Error: Error pulling data for job 829, executing attempt 2
Error: Error pulling data for job 829, executing attempt 3
Error: Error pulling data for job 829, ignoring row
Update: Pulling data for job 935
Error: Error pulling data for job 935, executing attempt 2
Error: Error pulling data for job 935, executing attempt 3
Error: Error pulling data for job 935, ignoring row
Update: Pulling data for job 940
Error: Error pulling data for job 940, executing attempt 2
Error: Error pulling data for job 940, executing attempt 3
Error: Error pulling data for job 940, ignoring row
Update: Pulling data for job 941
Error: Error pulling data for job 941, executing attempt 2

Error: Error pulling data for job 941, executing attempt 3
Error: Error pulling data for job 941, ignoring row
Update: Pulling data for job 1006
Error: Error pulling data for job 1006, executing attempt 2
Error: Error pulling data for job 1006, executing attempt 3
Error: Error pulling data for job 1006, ignoring row
Update: Pulling data for job 1017
Error: Error pulling data for job 1017, executing attempt 2
Error: Error pulling data for job 1017, executing attempt 3
Error: Error pulling data for job 1017, ignoring row
Update: Pulling data for job 1041
Error: Error pulling data for job 1041, executing attempt 2
Error: Error pulling data for job 1041, executing attempt 3
Error: Error pulling data for job 1041, ignoring row
Update: Pulling data for job 1045
Error: Error pulling data for job 1045, executing attempt 2
Error: Error pulling data for job 1045, executing attempt 3
Error: Error pulling data for job 1045, ignoring row
Update: Pulling data for job 1209
Error: Error pulling data for job 1209, executing attempt 2
Error: Error pulling data for job 1209, executing attempt 3
Error: Error pulling data for job 1209, ignoring row
Update: Pulling data for job 1244
Error: Error pulling data for job 1244, executing attempt 2
Error: Error pulling data for job 1244, executing attempt 3
Error: Error pulling data for job 1244, ignoring row
Update: Pulling data for job 1247
Error: Error pulling data for job 1247, executing attempt 2
Error: Error pulling data for job 1247, executing attempt 3
Error: Error pulling data for job 1247, ignoring row
Update: Pulling data for job 1286
Error: Error pulling data for job 1286, executing attempt 2
Error: Error pulling data for job 1286, executing attempt 3
Error: Error pulling data for job 1286, ignoring row
Update: Pulling data for job 1478
Error: Error pulling data for job 1478, executing attempt 2
Error: Error pulling data for job 1478, executing attempt 3
Error: Error pulling data for job 1478, ignoring row
Update: Pulling data for job 1484
Error: Error pulling data for job 1484, executing attempt 2
Error: Error pulling data for job 1484, executing attempt 3
Error: Error pulling data for job 1484, ignoring row
Update: Pulling data for job 1485
Error: Error pulling data for job 1485, executing attempt 2
Error: Error pulling data for job 1485, executing attempt 3
Error: Error pulling data for job 1485, ignoring row
Update: Pulling data for job 1486
Error: Error pulling data for job 1486, executing attempt 2
Error: Error pulling data for job 1486, executing attempt 3
Error: Error pulling data for job 1486, ignoring row
Update: Pulling data for job 1491
Error: Error pulling data for job 1491, executing attempt 2
Error: Error pulling data for job 1491, executing attempt 3
Error: Error pulling data for job 1491, ignoring row
Update: Pulling data for job 1563
Error: Error pulling data for job 1563, executing attempt 2
Error: Error pulling data for job 1563, executing attempt 3
Error: Error pulling data for job 1563, ignoring row
Update: Pulling data for job 1564
Error: Error pulling data for job 1564, executing attempt 2
Error: Error pulling data for job 1564, executing attempt 3
Error: Error pulling data for job 1564, ignoring row
Update: Pulling data for job 1816
Error: Error pulling data for job 1816, executing attempt 2
Error: Error pulling data for job 1816, executing attempt 3
Error: Error pulling data for job 1816, ignoring row
Update: Pulling data for job 1820
Error: Error pulling data for job 1820, executing attempt 2
Error: Error pulling data for job 1820, executing attempt 3
Error: Error pulling data for job 1820, ignoring row
Update: Pulling data for job 1821
Error: Error pulling data for job 1821, executing attempt 2
Error: Error pulling data for job 1821, executing attempt 3
Error: Error pulling data for job 1821, ignoring row
Update: Pulling data for job 1908
Error: Error pulling data for job 1908, executing attempt 2
Error: Error pulling data for job 1908, executing attempt 3
Error: Error pulling data for job 1908, ignoring row

In [17]:
##############################################################
# identify which job_pull failed second attempt - data ignored
##############################################################

print('Failed to retrieve {} items from site.\nIndex: {}'.format(
     len(job_pull_error_list_2), job_pull_error_list_2))

Failed to retrieve 60 items from site.
Index: [19, 34, 98, 101, 119, 134, 194, 197, 201, 205, 207, 256, 259, 270, 357, 364, 382, 384, 406, 426, 438, 451, 593, 626, 667, 671, 672, 675, 680, 686, 687, 688, 690, 691, 692, 693, 808, 829, 935, 940, 941, 1006, 1017, 1041, 1045, 1209, 1244, 1247, 1286, 1478, 1484, 1485, 1486, 1491, 1563, 1564, 1816, 1820, 1821, 1908]

In [18]:
##############################################################
# all web-jobs complete. closing driver.
##############################################################

driver.close()

In [21]:
##############################################################
# Data Cleaning
##############################################################

# reset the index of the dataframe
job_details.reset_index(drop=True, inplace=True)

# add back the column names 
job_details.columns = ['job_id', 'job_title', 'company_name', 'company_address', 
                       'job_category', 'job_url', 'job_description', 'job_requirements', 
                       'employment_type', 'seniority', 'job_skills',
                       'pay_min', 'pay_max', 'pay_type', 'posting_date', 'closing_date'
                       ]

job_count = len(job_details)

# remove entries from duplicated job_id (unique identifier)
job_details.drop_duplicates(subset='job_id', keep='first', inplace=True)
job_details.reset_index(drop=True, inplace=True)

print('{} duplicate entries were removed. \nCurrent Dataset contains {} entries'.format(\
      job_count - len(job_details), len(job_details)))

773 duplicate entries were removed.
Current Dataset contains 1093 entries

In [22]:
# show the final dataset
job_details

,job_id,job_title,company_name,company_address,job_category,job_url,job_description,job_requirements,employment_type,seniority,job_skills,pay_min,pay_max,pay_type,posting_date,closing_date
0,JOB-2019-0036660,Data Analyst (Data Science),BLACKBOX RESEARCH PTE LTD,"SINGAPORE POST CENTRE, 10 EUNOS ROAD 8 408600",Others,https://www.mycareersfuture.sg/job/data-analys...,"[As a Data Analyst, you will take charge of th...",[],Full Time,Executive,"[Analysis, Business Analysis, Clinical Data Ma...","$2,800","$3,600",Monthly,04 May 2019,03 Jun 2019
1,JOB-2019-0094697,Data Analyst (HR) (JD#5114),SCIENTE INTERNATIONAL PTE. LTD.,"THE SIGNATURE, 51 CHANGI BUSINESS PARK CENTRAL...",Information Technology,https://www.mycareersfuture.sg/job/data-analys...,[An exciting opportunity for Analytics profess...,"[Bachelor's degree, preferably in a field of A...",Permanent,Middle Management,"[Access, Analysis, Analytics, Business Analysi...","$7,000","$12,000",Monthly,04 May 2019,03 Jun 2019
2,JOB-2019-0094154,Risk and Financial Data Analyst,CARGILL TSF ASIA PTE. LTD.,"CAPITAGREEN, 138 MARKET STREET 048946",Banking and Finance,https://www.mycareersfuture.sg/job/risk-financ...,[Cargill Trade & Capital Markets (TCM) was est...,"[A technical background, preferably in Economi...",Full Time,Professional,"[Analysis, Banking, Credit Risk, Data Analysis...","$5,500","$8,250",Monthly,03 May 2019,02 Jun 2019
3,JOB-2019-0094456,Senior Data Analyst,JONES LANG LASALLE PROPERTY CONSULTANTS PTE LTD,"REPUBLIC PLAZA, 9 RAFFLES PLACE 048619",Real Estate / Property Management,https://www.mycareersfuture.sg/job/senior-data...,[JLL is looking for a Data Quality Analyst to ...,"[Good technical writing, documentation, and co...",Full Time,Senior Executive,"[Access, Analysis, Analytics, Business Analysi...","$5,000","$7,000",Monthly,03 May 2019,02 Jun 2019
4,JOB-2019-0094395,Data Analyst,CAPGEMINI SINGAPORE PTE. LTD.,6 BATTERY ROAD 049909,Banking and Finance,https://www.mycareersfuture.sg/job/data-analys...,[Analyst profile with understanding of both. T...,[],"Permanent, Full Time",Executive,"[Access, Business Analysis, Business Intellige...","$4,500","$6,500",Monthly,03 May 2019,02 Jun 2019
5,JOB-2019-0094277,Trade Data Analyst,COMMODITIES INTELLIGENCE CENTRE PTE. LTD.,"WHEELOCK PLACE, 501 ORCHARD ROAD 238880",Others,https://www.mycareersfuture.sg/job/trade-data-...,"[As part of CIC's rapid growing, we are lookin...",[],Full Time,Executive,"[Access, Analysis, Analytics, Biostatistics, B...","$4,000","$6,000",Monthly,03 May 2019,02 Jun 2019
6,JOB-2019-0092697,Data Analyst,BIO-RAD LABORATORIES (SINGAPORE) PTE LTD,NaN,Manufacturing,https://www.mycareersfuture.sg/job/data-analys...,[],"[Bachelor Degree in Economics, Statistics or M...",Permanent,Junior Executive,"[Access, Business Analysis, Business Intellige...","$3,500","$4,800",Monthly,03 May 2019,01 Jun 2019
7,JOB-2019-0093993,Data Management Specialist,STHREE PTE. LTD.,"CHINA SQUARE CENTRAL, 18 CROSS STREET 048423",Banking and Finance,https://www.mycareersfuture.sg/job/data-manage...,[The main responsibility of the position is to...,[Hands on and relevant experience in the above...,Contract,Professional,"[Access, Analysis, Analytics, Business Analysi...","$10,000","$12,000",Monthly,03 May 2019,02 Jun 2019
8,JOB-2019-0093684,Data Planner,CHEIL SINGAPORE PTE. LTD.,NaN,Advertising / Media,https://www.mycareersfuture.sg/job/data-planne...,"[2. , 3. ]",[ from campaign planning / execution / perform...,"Permanent, Full Time",Professional,"[Access, Business Analysis, Business Intellige...",NaN,NaN,NaN,03 May 2019,02 Jun 2019
9,JOB-2019-0093269,Data Analyst,OPTIMUM SOLUTIONS (SINGAPORE) PTE LTD,"PLAZA 8 @ CBP, 1 CHANGI BUSINESS PARK CRESCENT...",Information Technology,https://www.mycareersfuture.sg/job/data-analys...,[],"[BS in Mathematics, Economics, Computer Scienc...",Full Time,Executive,"[Active Directory, Cisco Technologies, Data Ce...","$4,000","$6,000",Monthly,02 May 2019,01 Jun 2019
10,JOB-2019-0092977,Senior Data Engineer / Data Engineer,NTUC ENTERPRISE NEXUS CO-OPERATIVE LIMITED,1 MARINA BOULEVARD 018989,Information Technology,https://www.mycareersfuture.sg/job/senior-data...,[],"[Advanced degree in computer science, computer...",Full Time,Executive,"[Access, Analysis, Analytics, Business Analysi...","$4,000","$8,000",Monthly,02 May 2019,01 Jun 2019
11,JOB-2019-0093087,Product Analyst,PROPERTYGURU PTE. LTD.,"TRIPLEONE SOMERSET, 111 SOMERSET ROAD 238164","Engineering, Information Technology",https://www.mycareersfuture.sg/job/product-ana...,[PropertyGuru Group is Asia’s leading online p...,[Bachelor’s degree in IT or relevant field. Al...,"Permanent, Full Time","Professional, Senior Executive","[Access, Analysis, Analytics, Business Analysi...","$7,000","$9,000",Monthly,02 May 2019,01 Jun 2019
12,JOB-2019-0091656,Data Analyst,SHIPSFOCUS INTELLIGENCE PTE. LTD.,"CONNEXIS, 1 FUSIONOPOLIS WAY 138632","Engineering, Information Technology, Others",https://www.mycareersfuture.sg/job/data-analys...,[Passionate in chemical shipping research? Cra...,[Experience in the Data Science & Engineering ...,"Permanent, Full Time","Fresh/entry level, Junior Executive","[Analysis, Business Analysis, Business Strateg...",NaN,NaN,NaN,30 Apr 2019,30 May 2019
13,JOB-2019-0091702,"Analyst, Operations Intelligence Data Science ...",DBS BANK LTD.,"MARINA BAY FINANCIAL CENTRE, 12 MARINA BOULEVA...",Banking and Finance,https://www.mycareersfuture.sg/job/analyst-ope...,[Group Technology and Operations (T&O) enables...,"[2 years experiences, Well versed with data po...","Permanent, Full Time",Executive,"[Analysis, Business Analysis, Business Strateg...","$2,550","$4,600",Monthly,30 Apr 2019,30 May 2019
14,JOB-2019-0019774,IT Executive (Data Analyst),SKY PREMIUM INTERNATIONAL PTE. LTD.,"ONE RAFFLES PLACE, 1 RAFFLES PLACE 048616",Information Technology,https://www.mycareersfuture.sg/job/executive-s...,[Sky Premium International is looking for IT E...,[],Full Time,Executive,"[Active Directory, Business Analysis, CRM, ERP...","$2,500","$4,000",Monthly,29 Apr 2019,29 May 2019
15,JOB-2019-0091291,Data Analyst,CAPGEMINI SINGAPORE PTE. LTD.,6 BATTERY ROAD 049909,Engineering,https://www.mycareersfuture.sg/job/data-analys...,[•Frontline team members who have to mix solid...,[],Permanent,Professional,"[Active Directory, Cisco Technologies, Data Ce...","$5,000","$7,500",Monthly,29 Apr 2019,29 May 2019
16,JOB-2019-0090798,Data Analyst [Powerbi] - 6 months,BUSINESS EDGE PERSONNEL SERVICES PTE LTD,"SINGAPORE SHOPPING CENTRE, 190 CLEMENCEAU AVEN...",Admin / Secretarial,https://www.mycareersfuture.sg/job/data-analys...,"[Location: Outram, Salary: up to $14.50 per ho...",[Diploma/Bachelor’s Degree in Statistics or An...,Contract,Executive,"[Analysis, Business Analysis, Clinical Data Ma...","$1,800","$2,300",Monthly,29 Apr 2019,29 May 2019
17,JOB-2019-0090963,"Senior Analyst, Data Architect",SCOOT TIGERAIR PTE. LTD.,"AIRLINE HOUSE, 25 AIRLINE ROAD 819829",Information Technology,https://www.mycareersfuture.sg/job/senior-anal...,[ ],[A Bachelor’s degree from an accredited colleg...,Full Time,Senior Executive,"[Active Directory, Business Analysis, Database...",NaN,NaN,NaN,29 Apr 2019,29 May 2019
18,JOB-2019-0091477,"VP / AVP, Wealth Mgmt Technical Business Analy...",DBS BANK LTD.,NaN,Banking and Finance,https://www.mycareersfuture.sg/job/vp-avp-weal...,[The new hire will support a portfolio of appl...,[At least 8-10 years’ experience in Wealth Man...,"Permanent, Full Time","Middle Management, Manager, Professional","[Business Development, Business Strategy, Cros...","$7,000","$14,000",Monthly,29 Apr 2019,29 May 2019
19,JOB-2019-0004573,Senior Data Analyst,STREETSINE SINGAPORE PTE. LTD.,"NEWS CENTRE, 1000 TOA PAYOH NORTH 318994",Information Technology,https://www.mycareersfuture.sg/job/senior-data...,[We are currently looking for a Senior Data An...,[Minimum 2 years of relevant work experience w...,"Permanent, Full Time","Professional, Executive","[Agile Methodologies, Business Analysis, Busin...","$4,000","$8,000",Monthly,26 Apr 2019,26 May 2019
20,JOB-2019-0089696,Mid Level Data Analyst,TRAVELOKA SERVICES PTE. LTD.,NaN,Information Technology,https://www.mycareersfuture.sg/job/mid-level-d...,[Data Analyst at Traveloka is at the forefront...,"[ \t, \t, \t, \t, \t, \t, \t, \t, \t, ...",Permanent,Junior Executive,"[.NET, Agile Methodologies, ASP.NET, Business ...","$4,300","$7,600",Monthly,26 Apr 2019,26 May 2019
21,JOB-2019-0089321,Platform Engineer,GUMI ASIA PTE. LTD.,"CONNEXIS, 1 FUSIONOPOLIS WAY 138632",Information Technology,https://www.mycareersfuture.sg/job/platform-en...,[Responsible for programming and maintaining m...,[Coding/Scripting experience in languages such...,Full Time,Executive,"[ActionScript, C#, C++, Computer Games, Direct...","$5,000","$6,500",Monthly,26 Apr 2019,26 May 2019
22,JOB-2019-0089689,Data Analytics Lead,TRAVELOKA SERVICES PTE. LTD.,NaN,Information Technology,https://www.mycareersfuture.sg/job/data-analyt...,"[You will be responsible for defining, collect...","[Passion in data analysis, mathematics, statis...",Permanent,Manager,"[Analysis, Analytics, Business Analytics, Busi...","$8,300","$15,000",Monthly,26 Apr 2019,26 May 2019
23,JOB-2019-0088666,Senior Data Analyst,PROPERTYGURU PTE. LTD.,"TRIPLEONE SOMERSET, 111 SOMERSET ROAD 238164","Engineering, Information Technology",https://www.mycareersfuture.sg/job/senior-data...,[PropertyGuru Group is Asia’s leading online p...,[Bachelor’s degree in IT or relevant field. Al...,"Permanent, Full Time","Professional, Senior Executive","[Access, Analysis, Analytics, Business Analysi...","$6,000","$8,000",Monthly,25 Apr 2019,25 May 2019
24,JOB-2019-0058738,Data Analyst,INNOSPIRE PTE. LTD.,NaN,Information Technology,https://www.mycareersfuture.sg/job/data-analys...,"[ , ]","[Degree in Mathematics, Economics, Computer Sc...",Permanent,Senior Executive,"[.NET, Agile Methodologies, CSS, Data Warehous...",NaN,NaN,NaN,25 Apr 2019,25 May 2019
25,JOB-2019-0088646,Data Engineer,Company Undisclosed,"MAPLETREE BUSINESS CITY, 30 PASIR PANJANG ROAD...",Advertising / Media,https://www.mycareersfuture.sg/job/data-engine...,[As Senior Data Engineer you will have a prove...,[6 years hands-on experience in the data platf...,Permanent,Professional,"[Access, Business Analysis, Business Intellige...","$8,000","$10,000",Monthly,25 Apr 2019,25 May 2019
26,JOB-2019-0087097,CRM Data Analyst,ASPIRE GLOBAL NETWORK PTE. LTD.,"CHINA SQUARE CENTRAL, 18 CROSS STREET 048423",Information Technology,https://www.mycareersfuture.sg/job/crm-data-an...,"[ , A well-established British recruitment com...","[At least 2 years of data analysis, coding and...",Permanent,Professional,"[Access, Business Analysis, Business Intellige...","$3,500","$6,200",Monthly,24 Apr 2019,24 May 2019
27,JOB-2019-0087076,CRM Data Analyst,ASPIRE GLOBAL NETWORK PTE. LTD.,"CHINA SQUARE CENTRAL, 18 CROSS STREET 048423",Information Technology,https://www.mycareersfuture.sg/job/crm-data-an...,[A well-established British recruitment compan...,"[At least 5 years of data analysis, coding and...",Permanent,"Professional, Executive","[.NET, Agile Methodologies, ASP.NET, Business ...","$6,000","$10,000",Monthly,24 Apr 2019,24 May 2019
28,JOB-2019-0045362,Data Analyst,ZEEMART PTE. LTD.,"TOWNERVILLE, 93 MCNAIR ROAD 328560",Information Technology,https://www.mycareersfuture.sg/job/data-analys...,[You will be part of a very vibrant and dynami...,[Analytical mind with sound business insights....,Full Time,Professional,"[Analysis, Business Analysis, Business Strateg...","$4,000","$6,000",Monthly,24 Apr 2019,24 May 2019
29,JOB-2019-0087316,Technical Data Analyst,ECLERX PRIVATE LIMITED,"HIGH STREET CENTRE, 1 NORTH BRIDGE ROAD 179094",Consulting,https://www.mycareersfuture.sg/job/technical-d...,[The successful candidate will be responsible ...,[],Contract,Professional,"[Analysis, Business Analysis, Business Intelli...","$8,000","$10,000",Monthly,24 Apr 2019,24 May 2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,JOB-2019-0082215,DFS Strategy AAP,DAIMLER FINANCIAL SERVICES AFRICA & ASIA PACIF...,"WESTGATE TOWER, 1 GATEWAY DRIVE 608531",Marketing / Public Relations,https://www.mycareersfuture.sg/job/dfs-strateg...,[- Drive and support the strategy process in D...,[],"Permanent, Contract",Professional,"[Advertising, Business Development, Business S...","$5,000","$8,000",Monthly,17 Apr 2019,17 May 2019
1064,JOB-2019-0082918,IT Support Executive [Pioneer / 5 days / H...,THE SUPREME HR ADVISORY PTE. LTD.,"AZ @ PAYA LEBAR, 140 PAYA LEBAR ROAD 409015",Engineering,https://www.mycareersfuture.sg/job/support-exe...,[- Provide hardware support and first line res...,[2 years practical experience in SAP Business ...,"Permanent, Full Time",Senior Executive,"[Active Directory, Business Analysis, Change M...","$4,000","$4,500",Monthly,17 Apr 2019,17 May 2019
1065,JOB-2019-0082863,"Director, Sales",Company Undisclosed,NaN,Logistics / Supply Chain,https://www.mycareersfuture.sg/job/director-sa...,"[ , business relationships at all...",[Exceptional relationship management & communi...,Permanent,Middle Management,"[Business Development, Business Strategy, Chan...","$10,000","$15,000",Monthly,17 Apr 2019,17 May 2019
1066,JOB-2019-0080804,Software and Applications Developer and Analys...,RECRUITFIRST PTE. LTD.,6 BATTERY ROAD 049909,Information Technology,https://www.mycareersfuture.sg/job/software-ap...,[As part of the Finance Systems/Applications t...,[Bachelor's Degree in Computer Science / Infor...,"Contract, Full Time",Professional,"[.NET, Agile Methodologies, ASP.NET, C#, C++, ...","$4,000","$7,000",Monthly,16 Apr 2019,16 May 2019
1067,JOB-2019-0081612,Senior Platform Engineer,VIKI PRIVATE LIMITED,"CAPITAGREEN, 138 MARKET STREET 048946",Engineering,https://www.mycareersfuture.sg/job/senior-plat...,[],[],Full Time,Professional,"[C, C++, Embedded Systems, Engineering, Engine...","$8,000","$10,000",Monthly,16 Apr 2019,16 May 2019
1068,JOB-2019-0081448,Platform Engineer,VIKI PRIVATE LIMITED,"CAPITAGREEN, 138 MARKET STREET 048946",Engineering,https://www.mycareersfuture.sg/job/platform-en...,[],[],Full Time,Professional,"[AutoCAD, C, C++, Engineering, Integration, Ja...","$6,000","$8,000",Monthly,16 Apr 2019,16 May 2019
1069,JOB-2019-0081810,Application Analyst,EPS CONSULTANTS PTE LTD,"SPORE BUSINESS FEDERATION CTR, 160 ROBINSON RO...",Information Technology,https://www.mycareersfuture.sg/job/application...,[],"[Degree in Information Systems., At least 5 ye...",Contract,Senior Executive,"[Access, Analysis, Business Analysis, EHR, EMR...","$4,500","$6,000",Monthly,16 Apr 2019,16 May 2019
1070,JOB-2019-0081803,Software Engineer - Competitive Pricing,FOODPANDA SINGAPORE PTE. LTD.,"GB BUILDING, 143 CECIL STREET 069542","Engineering, Information Technology",https://www.mycareersfuture.sg/job/software-en...,[“There is no love sincerer than the love of f...,"[ \t, \t, \t, \t, \t, \t, \t, \t, \t, ...",Full Time,"Executive, Junior Executive","[Business Analysis, Business Process Improveme...","$3,500","$7,000",Monthly,16 Apr 2019,16 May 2019
1071,JOB-2019-0080157,Project Manager- Business Intelligence,EIRE SYSTEMS SINGAPORE PTE. LTD.,"KEPPEL BAY TOWER, 1 HARBOURFRONT AVENUE 098632",Information Technology,https://www.mycareersfuture.sg/job/project-man...,[We are looking to hire a Project manager with...,"[Proven, complex project management capability...",Full Time,Manager,"[Budgets, Business Analysis, Business Developm...","$7,000","$10,000",Monthly,15 Apr 2019,15 May 2019
1072,JOB-2019-0079550,Analytics Engineer,ST ENGINEERING MANAGEMENT SERVICES PTE. LTD.,"ST ENGINEERING HUB, 1 ANG MO KIO ELECTRONICS P...",Information Technology,https://www.mycareersfuture.sg/job/analytics-e...,[The Analytics System team is seeking an excep...,"[Knows Tableau, D3,.NET Programming, C, Java S...",Permanent,Executive,"[Agile Methodologies, C, C#, C++, CSS, Eclipse...","$5,000","$8,000",Monthly,15 Apr 2019,15 May 2019
1073,JOB-2019-0079262,Associate Incentives Accounting,SABRE ASIA PACIFIC PTE. LTD.,"ABACUS PLAZA, 3 TAMPINES CENTRAL 1 529540",Accounting / Auditing / Taxation,https://www.mycareersfuture.sg/job/associate-i...,[Sabre is a technology solutions provider to t...,[],Full Time,Executive,"[Account Reconciliation, Accounting, Accounts ...","$34,700","$64,500",Annually,15 Apr 2019,15 May 2019
1074,JOB-2019-0041546,Marketing and Admin Executive,FITNESS FACTORY PTE. LTD.,82 BOAT QUAY 049870,"Admin / Secretarial, Customer Service, Marketi...",https://www.mycareersfuture.sg/job/marketing-a...,[Provide support in Marketing and Administrati...,[Diploma in Mass Communication/Marketing or eq...,Full Time,Fresh/entry level,"[Advertising, Customer Service, Digital Market...","$1,800","$2,200",Monthly,15 Apr 2019,15 May 2019
1075,JOB-2019-0079192,"Technology Risk Associate (FAIT), Advisory, Si...",ERNST & YOUNG ADVISORY PTE. LTD.,1 RAFFLES QUAY 048583,Accounting / Auditing / Taxation,https://www.mycareersfuture.sg/job/technology-...,[Our Technology Risk services are designed for...,"[A recognized university degree in accounting,...",Permanent,Executive,"[Auditing, Business Continuity, Business Proce...","$3,000","$6,000",Monthly,14 Apr 2019,14 May 2019
1076,JOB-2019-0079191,Technology Risk Senior Associate (Financial Au...,ERNST & YOUNG ADVISORY PTE. LTD.,1 RAFFLES QUAY 048583,Accounting / Auditing / Taxation,https://www.mycareersfuture.sg/job/technology-...,[Our Technology Risk services are designed for...,"[A recognized university degree in accounting,...",Permanent,Executive,"[Auditing, Business Continuity, Business Proce...","$4,100","$8,200",Monthly,14 Apr 2019,14 May 2019
1077,JOB-2019-0079193,"Technology Risk Manager (Financial Audit IT), ...",ERNST & YOUNG ADVISORY PTE. LTD.,1 RAFFLES QUAY 048583,Accounting / Auditing / Taxation,https://www.mycareersfuture.sg/job/technology-...,[Our Technology Risk services are designed for...,"[ , , , , , , , , , , , , , , , ...",Permanent,Manager,"[Auditing, Business Process, Change Management...","$6,000","$12,000",Monthly,14 Apr 2019,14 May 2019
1078,JOB-2019-0077868,Research Fellow,NATIONAL UNIVERSITY OF SINGAPORE,21 LOWER KENT RIDGE ROAD 119077,Sciences / Laboratory / R&D,https://www.mycareersfuture.sg/job/research-fe...,"[ , , The National University of Singapore in...","[A PhD degree in a relevant area;, Good public...",Full Time,Professional,"[Algorithms, Artificial Intelligence, Biochemi...","$6,000","$7,200",Monthly,12 Apr 2019,12 May 2019
1079,JOB-2019-0077557,AX Technical Consultant,GOODRICH GLOBAL PTE. LTD.,"GOODRICH BUILDING, 8 CHANGI SOUTH LANE 486113",Information Technology,https://www.mycareersfuture.sg/job/ax-technica...,[1. Maintain and support daily operations or i...,[],Permanent,Professional,"[Agile Methodologies, Business Analysis, Busin...",NaN,NaN,NaN,11 Apr 2019,11 May 2019
1080,JOB-2019-0076443,Deployment Project Manager,TECH MAHINDRA LIMITED (SINGAPORE BRANCH),"HONEYWELL BUILDING, 17 CHANGI BUSINESS PARK CE...",Information Technology,https://www.mycareersfuture.sg/job/deployment-...,[Minimum five (5) years of IT experience with ...,[],Permanent,Executive,"[Budgets, Business Analysis, Business Developm...","$6,500","$7,500",Monthly,10 Apr 2019,10 May 2019
1081,JOB-2019-0074900,Procurement Business Intelligence (19001366),GLOBALFOUNDRIES SINGAPORE PTE. LTD.,60 WOODLANDS IND PARK D STREET 2 738406,"Information Technology, Purchasing / Merchandi...",https://www.mycareersfuture.sg/job/procurement...,[GLOBALFOUNDRIES Global Supply Management (GSM...,"[B.S. Degree in Business, Information Systems ...","Permanent, Full Time",Executive,"[Analysis, Budgets, Contract Management, Contr...","$5,400","$8,000",Monthly,09 Apr 2019,09 May 2019

In [23]:
##############################################################
# Do some basic data formatting
##############################################################


output = job_details.copy()
output['job_requirements'] = output['job_requirements'].map(lambda x: ' '.join(x))
output['job_description'] = output['job_description'].map(lambda x: ' '.join(x).replace('\xa0',''))

In [24]:
##############################################################
# export data into csv file
##############################################################

output.to_csv('./job_openings.csv')

In [25]:
# ##############################################################
# # manual execution - pull the failed jobs again
# ##############################################################

# driver = webdriver.Chrome(chromedriver, chrome_options = chrome_options)

# for row_count in [139]: 

#     print('Update: Pulling data for job {}'.format(row_count))
#     try:
#         job_details = job_details.append([pull_job_details(job_links[row_count], 'mcf')])
#     except:
#         print('Error: Error pulling data for job {}, executing attempt 2'.format(row_count))
#         try:
#             job_details = job_details.append([pull_job_details(job_links[row_count], 'mcf')])
#         except:
#             print('Error: Error pulling data for job {}, executing attempt 3'.format(row_count))
#             try:
#                 job_details = job_details.append([pull_job_details(job_links[row_count], 'mcf')])
#             except:
#                 print('Error: Error pulling data for job {}, ignoring row'.format(row_count))
#                 job_pull_error_list_2.append(row_count)

# driver.close()

In [26]:
job_details.isnull().sum()

job_id                0
job_title             0
company_name          0
company_address     196
job_category          0
job_url               0
job_description       0
job_requirements      0
employment_type       0
seniority             0
job_skills            0
pay_min              82
pay_max              82
pay_type             82
posting_date          0
closing_date          0
dtype: int64